// Copyright 2022 Gaming Research Integration for Learning Lab. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"
#include "FuseType.generated.h"

//Blueprints don't currently support non-uint8 enums.
UENUM()
enum class EFuseType : uint16
{
	Other,
	IntelligentInfluence = 10U UMETA(DisplayName = "Intelligent Influence"),
	Sensor = 20U UMETA(DisplayName = "Sensor"),
	Selfdestruct = 30U UMETA(DisplayName = "Self-destruct"),
	UltraQuick = 40U UMETA(DisplayName = "Ultra Quick"),
	Body = 50U UMETA(DisplayName = "Body"),
	DeepIntrusion = 60U UMETA(DisplayName = "Deep Intrusion"),
	Multifunction = 100U UMETA(DisplayName = "Multifunction"),
	PointDetonationPD = 200U UMETA(DisplayName = "Point Detonation (PD)"),
	BaseDetonationBD = 300U UMETA(DisplayName = "Base Detonation (BD)"),
	Contact = 1000U UMETA(DisplayName = "Contact"),
	Contact_InstantImpact = 1100U UMETA(DisplayName = "Contact, Instant (Impact)"),
	Contact_Delayed = 1200U UMETA(DisplayName = "Contact, Delayed"),
	TenMsDelay_New = 1201U UMETA(DisplayName = "10 ms delay (New)"),
	TwentyMsDelay_New = 1202U UMETA(DisplayName = "20 ms delay (New)"),
	FiftyMsDelay_New = 1205U UMETA(DisplayName = "50 ms delay (New)"),
	SixtyMsDelay_New = 1206U UMETA(DisplayName = "60 ms delay (New)"),
	OneHundredMsDelay_New = 1210U UMETA(DisplayName = "100 ms delay (New)"),
	OneTwentyFiveMsDelay_New = 1212U UMETA(DisplayName = "125 ms delay (New)"),
	TwoFiftyMsDelay_New = 1225U UMETA(DisplayName = "250 ms delay (New)"),
	FiveMsDelay = 1250U UMETA(DisplayName = "5 ms delay"),
	FifteenMsDelay = 1251U UMETA(DisplayName = "15 ms delay"),
	TwentyFiveMsDelay = 1252U UMETA(DisplayName = "25 ms delay"),
	ThirtyMsDelay = 1253U UMETA(DisplayName = "30 ms delay"),
	ThirtyFiveMsDelay = 1254U UMETA(DisplayName = "35 ms delay"),
	FourtyMsDelay = 1255U UMETA(DisplayName = "40 ms delay"),
	FourtyFiveMsDelay = 1256U UMETA(DisplayName = "45 ms delay"),
	NinetyMsDelay = 1257U UMETA(DisplayName = "90 ms delay"),
	OneTwentyMsDelay = 1258U UMETA(DisplayName = "120 ms delay"),
	OneEightyMsDelay = 1259U UMETA(DisplayName = "180 ms delay"),
	TwoFortyMsDelay = 1260U UMETA(DisplayName = "240 ms delay"),
	Contact_ElectronicObliqueContact = 1300U UMETA(DisplayName = "Contact, Electronic (Oblique Contact)"),
	Contact_Graze = 1400U UMETA(DisplayName = "Contact, Graze"),
	Contact_Crush = 1500U UMETA(DisplayName = "Contact, Crush"),
	Contact_Hydrostatic = 1600U UMETA(DisplayName = "Contact, Hydrostatic"),
	Contact_Mechanical = 1700U UMETA(DisplayName = "Contact, Mechanical"),
	Contact_Chemical = 1800U UMETA(DisplayName = "Contact, Chemical"),
	Contact_Piezoelectric = 1900U UMETA(DisplayName = "Contact, Piezoelectric"),
	Contact_PointInitiating = 1910U UMETA(DisplayName = "Contact, Point Initiating"),
	Contact_PointInitiating_BaseDetonating = 1920U UMETA(DisplayName = "Contact, Point Initiating, Base Detonating"),
	Contact_BaseDetonating = 1930U UMETA(DisplayName = "Contact, Base Detonating"),
	Contact_BallisticCapandBase = 1940U UMETA(DisplayName = "Contact, Ballistic Cap and Base"),
	Contact_Base = 1950U UMETA(DisplayName = "Contact, Base"),
	Contact_Nose = 1960U UMETA(DisplayName = "Contact, Nose"),
	Contact_FittedinStandoffProbe = 1970U UMETA(DisplayName = "Contact, Fitted in Standoff Probe"),
	Contact_Nonaligned = 1980U UMETA(DisplayName = "Contact, Non-aligned"),
	Timed = 2000U UMETA(DisplayName = "Timed"),
	Timed_Programmable = 2100U UMETA(DisplayName = "Timed, Programmable"),
	Timed_Burnout = 2200U UMETA(DisplayName = "Timed, Burnout"),
	Timed_Pyrotechnic = 2300U UMETA(DisplayName = "Timed, Pyrotechnic"),
	Timed_Electronic = 2400U UMETA(DisplayName = "Timed, Electronic"),
	Timed_BaseDelay = 2500U UMETA(DisplayName = "Timed, Base Delay"),
	Timed_ReinforcedNoseImpactDelay = 2600U UMETA(DisplayName = "Timed, Reinforced Nose Impact Delay"),
	Timed_ShortDelayImpact = 2700U UMETA(DisplayName = "Timed, Short Delay Impact"),
	TenMsDelay = 2701U UMETA(DisplayName = "10 ms delay"),
	TwentyMsDelay = 2702U UMETA(DisplayName = "20 ms delay"),
	FiftyMsDelay = 2705U UMETA(DisplayName = "50 ms delay"),
	SixtyMsDelay = 2706U UMETA(DisplayName = "60 ms delay"),
	OneHundredMsDelay = 2710U UMETA(DisplayName = "100 ms delay"),
	OneTwentyFiveMsDelay = 2712U UMETA(DisplayName = "125 ms delay"),
	TwoFiftyMsDelay = 2725U UMETA(DisplayName = "250 ms delay"),
	Timed_NoseMountedVariableDelay = 2800U UMETA(DisplayName = "Timed, Nose Mounted Variable Delay"),
	Timed_LongDelaySide = 2900U UMETA(DisplayName = "Timed, Long Delay Side"),
	Timed_SelectableDelay = 2910U UMETA(DisplayName = "Timed, Selectable Delay"),
	Timed_Impact = 2920U UMETA(DisplayName = "Timed, Impact"),
	Timed_Sequence = 2930U UMETA(DisplayName = "Timed, Sequence"),
	Proximity = 3000U UMETA(DisplayName = "Proximity"),
	Proximity_ActiveLaser = 3100U UMETA(DisplayName = "Proximity, Active Laser"),
	Proximity_MagneticMagpolarity = 3200U UMETA(DisplayName = "Proximity, Magnetic (Magpolarity)"),
	Proximity_ActiveRadarDopplerRadar = 3300U UMETA(DisplayName = "Proximity, Active Radar (Doppler Radar)"),
	Proximity_RadioFrequencyRF = 3400U UMETA(DisplayName = "Proximity, Radio Frequency (RF)"),
	Proximity_Programmable = 3500U UMETA(DisplayName = "Proximity, Programmable"),
	Proximity_Programmable_Prefragmented = 3600U UMETA(DisplayName = "Proximity, Programmable, Prefragmented"),
	Proximity_Infrared = 3700U UMETA(DisplayName = "Proximity, Infrared"),
	Command = 4000U UMETA(DisplayName = "Command"),
	Command_Electronic_RemotelySet = 4100U UMETA(DisplayName = "Command, Electronic, Remotely Set"),
	Altitude = 5000U UMETA(DisplayName = "Altitude"),
	Altitude_RadioAltimeter = 5100U UMETA(DisplayName = "Altitude, Radio Altimeter"),
	Altitude_AirBurst = 5200U UMETA(DisplayName = "Altitude, Air Burst"),
	Depth = 6000U UMETA(DisplayName = "Depth"),
	Acoustic = 7000U UMETA(DisplayName = "Acoustic"),
	Pressure = 8000U UMETA(DisplayName = "Pressure"),
	Pressure_Delay = 8010U UMETA(DisplayName = "Pressure, Delay"),
	Inert = 8100U UMETA(DisplayName = "Inert"),
	Dummy = 8110U UMETA(DisplayName = "Dummy"),
	Practice = 8120U UMETA(DisplayName = "Practice"),
	PlugRepresenting = 8130U UMETA(DisplayName = "Plug Representing"),
	Training = 8150U UMETA(DisplayName = "Training"),
	Pyrotechnic = 9000U UMETA(DisplayName = "Pyrotechnic"),
	Pyrotechnic_Delay = 9010U UMETA(DisplayName = "Pyrotechnic, Delay"),
	Electrooptical = 9100U UMETA(DisplayName = "Electro-optical"),
	Electromechanical = 9110U UMETA(DisplayName = "Electromechanical"),
	Electromechanical_Nose = 9120U UMETA(DisplayName = "Electromechanical, Nose"),
	Strikerless = 9200U UMETA(DisplayName = "Strikerless"),
	Strikerless_NoseImpact = 9210U UMETA(DisplayName = "Strikerless, Nose Impact"),
	Strikerless_CompressionIgnition = 9220U UMETA(DisplayName = "Strikerless, Compression-Ignition"),
	CompressionIgnition = 9300U UMETA(DisplayName = "Compression-Ignition"),
	CompressionIgnition_Strikerless_NoseImpact = 9310U UMETA(DisplayName = "Compression-Ignition, Strikerless, Nose Impact"),
	Percussion = 9400U UMETA(DisplayName = "Percussion"),
	Percussion_Instantaneous = 9410U UMETA(DisplayName = "Percussion, Instantaneous"),
	Electronic = 9500U UMETA(DisplayName = "Electronic"),
	Electronic_InternallyMounted = 9510U UMETA(DisplayName = "Electronic, Internally Mounted"),
	Electronic_RangeSetting = 9520U UMETA(DisplayName = "Electronic, Range Setting"),
	Electronic_Programmed = 9530U UMETA(DisplayName = "Electronic, Programmed"),
	Mechanical = 9600U UMETA(DisplayName = "Mechanical"),
	Mechanical_Nose = 9610U UMETA(DisplayName = "Mechanical, Nose"),
	Mechanical_Tail = 9620U UMETA(DisplayName = "Mechanical, Tail"),
};