// Copyright 2022 Gaming Research Integration for Learning Lab. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"
#include "VariableRecordTypes.generated.h"

//Blueprints don't currently support non-uint8 enums.
UENUM()
enum class EVariableRecordTypes : uint32
{
	Other_Zero,
	HighFidelityHAVEQUICKRadio = 3000U UMETA(DisplayName = "High Fidelity HAVE QUICK Radio"),
	BlankingSectorattributerecord = 3500U UMETA(DisplayName = "Blanking Sector attribute record"),
	AngleDeceptionattributerecord = 3501U UMETA(DisplayName = "Angle Deception attribute record"),
	FalseTargetsattributerecord = 3502U UMETA(DisplayName = "False Targets attribute record"),
	DEPrecisionAimpointrecord = 4000U UMETA(DisplayName = "DE Precision Aimpoint record"),
	DEAreaAimpointrecord = 4001U UMETA(DisplayName = "DE Area Aimpoint record"),
	DirectedEnergyDamageDescriptionrecord = 4500U UMETA(DisplayName = "Directed Energy Damage Description record"),
	CryptoControl = 5000U UMETA(DisplayName = "Crypto Control"),
	Mode5_STransponderLocation = 5001U UMETA(DisplayName = "Mode 5/S Transponder Location"),
	Mode5_STransponderLocationError = 5002U UMETA(DisplayName = "Mode 5/S Transponder Location Error"),
	SquitterAirbornePositionReport = 5003U UMETA(DisplayName = "Squitter Airborne Position Report"),
	SquitterAirborneVelocityReport = 5004U UMETA(DisplayName = "Squitter Airborne Velocity Report"),
	SquitterSurfacePositionReport = 5005U UMETA(DisplayName = "Squitter Surface Position Report"),
	SquitterIdentificationReport = 5006U UMETA(DisplayName = "Squitter Identification Report"),
	GICB = 5007U UMETA(DisplayName = "GICB"),
	SquitterEventDrivenReport = 5008U UMETA(DisplayName = "Squitter Event-Driven Report"),
	AntennaLocation = 5009U UMETA(DisplayName = "Antenna Location"),
	BasicInteractive = 5010U UMETA(DisplayName = "Basic Interactive"),
	InteractiveMode4Reply = 5011U UMETA(DisplayName = "Interactive Mode 4 Reply"),
	InteractiveMode5Reply = 5012U UMETA(DisplayName = "Interactive Mode 5 Reply"),
	InteractiveBasicMode5 = 5013U UMETA(DisplayName = "Interactive Basic Mode 5"),
	InteractiveBasicModeS = 5014U UMETA(DisplayName = "Interactive Basic Mode S"),
	IOEffect = 5500U UMETA(DisplayName = "IO Effect"),
	IOCommunicationsNode = 5501U UMETA(DisplayName = "IO Communications Node"),
	Identification = 10000U UMETA(DisplayName = "Identification"),
	EntityType = 11000U UMETA(DisplayName = "Entity Type"),
	Concatenated = 11100U UMETA(DisplayName = "Concatenated"),
	Kind_New = 11110U UMETA(DisplayName = "Kind (New)"),
	Domain_New = 11120U UMETA(DisplayName = "Domain (New)"),
	Country_New = 11130U UMETA(DisplayName = "Country (New)"),
	Category_New = 11140U UMETA(DisplayName = "Category (New)"),
	Subcategory_New = 11150U UMETA(DisplayName = "Subcategory (New)"),
	Specific_New = 11160U UMETA(DisplayName = "Specific (New)"),
	Extra_New = 11170U UMETA(DisplayName = "Extra (New)"),
	ForceID = 11200U UMETA(DisplayName = "Force ID"),
	Description_New = 11300U UMETA(DisplayName = "Description (New)"),
	AlternativeEntityType = 12000U UMETA(DisplayName = "Alternative Entity Type"),
	Kind_AlsoNew = 12110U UMETA(DisplayName = "Kind (Also New)"),
	Domain_AlsoNew = 12120U UMETA(DisplayName = "Domain (Also New)"),
	Country_AlsoNew = 12130U UMETA(DisplayName = "Country (Also New)"),
	Category_AlsoNew = 12140U UMETA(DisplayName = "Category (Also New)"),
	Subcategory_AlsoNew = 12150U UMETA(DisplayName = "Subcategory (Also New)"),
	Specific_AlsoNew = 12160U UMETA(DisplayName = "Specific (Also New)"),
	Extra_AlsoNew = 12170U UMETA(DisplayName = "Extra (Also New)"),
	Description_AlsoNew = 12300U UMETA(DisplayName = "Description (Also New)"),
	EntityMarking = 13000U UMETA(DisplayName = "Entity Marking"),
	EntityMarkingCharacters = 13100U UMETA(DisplayName = "Entity Marking Characters"),
	CrewID = 13200U UMETA(DisplayName = "Crew ID"),
	TaskOrganization = 14000U UMETA(DisplayName = "Task Organization"),
	RegimentName = 14200U UMETA(DisplayName = "Regiment Name"),
	BattalionName = 14300U UMETA(DisplayName = "Battalion Name"),
	CompanyName = 14400U UMETA(DisplayName = "Company Name"),
	PlatoonName = 14500U UMETA(DisplayName = "Platoon Name"),
	SquadName = 14520U UMETA(DisplayName = "Squad Name"),
	TeamName = 14540U UMETA(DisplayName = "Team Name"),
	BumperNumber = 14600U UMETA(DisplayName = "Bumper Number"),
	VehicleNumber = 14700U UMETA(DisplayName = "Vehicle Number"),
	UnitNumber = 14800U UMETA(DisplayName = "Unit Number"),
	DISIdentity = 15000U UMETA(DisplayName = "DIS Identity"),
	DISSiteID = 15100U UMETA(DisplayName = "DIS Site ID"),
	DISHostID = 15200U UMETA(DisplayName = "DIS Host ID"),
	DISEntityID = 15300U UMETA(DisplayName = "DIS Entity ID"),
	MountIntent = 15400U UMETA(DisplayName = "Mount Intent"),
	TetherUnthetherCommandID = 15500U UMETA(DisplayName = "Tether-Unthether Command ID"),
	TeleportEntityDataRecord = 15510U UMETA(DisplayName = "Teleport Entity Data Record"),
	DISAggregateIDSetifcommunicationtoaggregate = 15600U UMETA(DisplayName = "DIS Aggregate ID (Set if communication to aggregate)"),
	OwnershipStatus = 15800U UMETA(DisplayName = "Ownership Status"),
	Loads = 20000U UMETA(DisplayName = "Loads"),
	CrewMembers = 21000U UMETA(DisplayName = "Crew Members"),
	CrewMemberID = 21100U UMETA(DisplayName = "Crew Member ID"),
	Health = 21200U UMETA(DisplayName = "Health"),
	JobAssignment = 21300U UMETA(DisplayName = "Job Assignment"),
	Fuel = 23000U UMETA(DisplayName = "Fuel"),
	Quantity = 23100U UMETA(DisplayName = "Quantity"),
	Quantity_New = 23105U UMETA(DisplayName = "Quantity (New)"),
	Ammunition = 24000U UMETA(DisplayName = "Ammunition"),
	OneHundredTwentymmHEAT_quantity = 24001U UMETA(DisplayName = "120-mm HEAT, quantity"),
	OneHundredTwentymmSABOT_quantity = 24002U UMETA(DisplayName = "120-mm SABOT, quantity"),
	Twelve_7mmM8_quantity = 24003U UMETA(DisplayName = "12.7-mm M8, quantity"),
	Twelve_7mmM20_quantity = 24004U UMETA(DisplayName = "12.7-mm M20, quantity"),
	Seven_62mmM62_quantity = 24005U UMETA(DisplayName = "7.62-mm M62, quantity"),
	M250UKL8A1_quantity = 24006U UMETA(DisplayName = "M250 UKL8A1, quantity"),
	M250UKL8A3_quantity = 24007U UMETA(DisplayName = "M250 UKL8A3, quantity"),
	Seven_62mmM80_quantity = 24008U UMETA(DisplayName = "7.62-mm M80, quantity"),
	Twelve_7mm_quantity = 24009U UMETA(DisplayName = "12.7-mm, quantity"),
	Seven_62mm_quantity = 24010U UMETA(DisplayName = "7.62-mm, quantity"),
	Mines_quantity = 24060U UMETA(DisplayName = "Mines, quantity"),
	Type = 24100U UMETA(DisplayName = "Type"),
	Kind = 24110U UMETA(DisplayName = "Kind"),
	Domain = 24120U UMETA(DisplayName = "Domain"),
	Country = 24130U UMETA(DisplayName = "Country"),
	Category = 24140U UMETA(DisplayName = "Category"),
	Subcategory = 24150U UMETA(DisplayName = "Subcategory"),
	Extra = 24160U UMETA(DisplayName = "Extra"),
	Description = 24300U UMETA(DisplayName = "Description"),
	Cargo = 25000U UMETA(DisplayName = "Cargo"),
	VehicleMass = 26000U UMETA(DisplayName = "Vehicle Mass"),
	SupplyQuantity = 27000U UMETA(DisplayName = "Supply Quantity"),
	Armament = 28000U UMETA(DisplayName = "Armament"),
	Status = 30000U UMETA(DisplayName = "Status"),
	Activateentity = 30010U UMETA(DisplayName = "Activate entity"),
	SubscriptionState = 30100U UMETA(DisplayName = "Subscription State"),
	Roundtriptimedelay = 30300U UMETA(DisplayName = "Round trip time delay"),
	TADILJmessagecountlabel0 = 30400U UMETA(DisplayName = "TADIL J message count (label 0)"),
	TADILJmessagecountlabel1 = 30401U UMETA(DisplayName = "TADIL J message count (label 1)"),
	TADILJmessagecountlabel2 = 30402U UMETA(DisplayName = "TADIL J message count (label 2)"),
	TADILJmessagecountlabel3 = 30403U UMETA(DisplayName = "TADIL J message count (label 3)"),
	TADILJmessagecountlabel4 = 30404U UMETA(DisplayName = "TADIL J message count (label 4)"),
	TADILJmessagecountlabel5 = 30405U UMETA(DisplayName = "TADIL J message count (label 5)"),
	TADILJmessagecountlabel6 = 30406U UMETA(DisplayName = "TADIL J message count (label 6)"),
	TADILJmessagecountlabel7 = 30407U UMETA(DisplayName = "TADIL J message count (label 7)"),
	TADILJmessagecountlabel8 = 30408U UMETA(DisplayName = "TADIL J message count (label 8)"),
	TADILJmessagecountlabel9 = 30409U UMETA(DisplayName = "TADIL J message count (label 9)"),
	TADILJmessagecountlabel10 = 30410U UMETA(DisplayName = "TADIL J message count (label 10)"),
	TADILJmessagecountlabel11 = 30411U UMETA(DisplayName = "TADIL J message count (label 11)"),
	TADILJmessagecountlabel12 = 30412U UMETA(DisplayName = "TADIL J message count (label 12)"),
	TADILJmessagecountlabel13 = 30413U UMETA(DisplayName = "TADIL J message count (label 13)"),
	TADILJmessagecountlabel14 = 30414U UMETA(DisplayName = "TADIL J message count (label 14)"),
	TADILJmessagecountlabel15 = 30415U UMETA(DisplayName = "TADIL J message count (label 15)"),
	TADILJmessagecountlabel16 = 30416U UMETA(DisplayName = "TADIL J message count (label 16)"),
	TADILJmessagecountlabel17 = 30417U UMETA(DisplayName = "TADIL J message count (label 17)"),
	TADILJmessagecountlabel18 = 30418U UMETA(DisplayName = "TADIL J message count (label 18)"),
	TADILJmessagecountlabel19 = 30419U UMETA(DisplayName = "TADIL J message count (label 19)"),
	TADILJmessagecountlabel20 = 30420U UMETA(DisplayName = "TADIL J message count (label 20)"),
	TADILJmessagecountlabel21 = 30421U UMETA(DisplayName = "TADIL J message count (label 21)"),
	TADILJmessagecountlabel22 = 30422U UMETA(DisplayName = "TADIL J message count (label 22)"),
	TADILJmessagecountlabel23 = 30423U UMETA(DisplayName = "TADIL J message count (label 23)"),
	TADILJmessagecountlabel24 = 30424U UMETA(DisplayName = "TADIL J message count (label 24)"),
	TADILJmessagecountlabel25 = 30425U UMETA(DisplayName = "TADIL J message count (label 25)"),
	TADILJmessagecountlabel26 = 30426U UMETA(DisplayName = "TADIL J message count (label 26)"),
	TADILJmessagecountlabel27 = 30427U UMETA(DisplayName = "TADIL J message count (label 27)"),
	TADILJmessagecountlabel28 = 30428U UMETA(DisplayName = "TADIL J message count (label 28)"),
	TADILJmessagecountlabel29 = 30429U UMETA(DisplayName = "TADIL J message count (label 29)"),
	TADILJmessagecountlabel30 = 30430U UMETA(DisplayName = "TADIL J message count (label 30)"),
	TADILJmessagecountlabel31 = 30431U UMETA(DisplayName = "TADIL J message count (label 31)"),
	Position = 31000U UMETA(DisplayName = "Position"),
	RouteWaypointtype = 31010U UMETA(DisplayName = "Route (Waypoint) type"),
	MilGrid10 = 31100U UMETA(DisplayName = "MilGrid10"),
	GeocentricCoordinates = 31200U UMETA(DisplayName = "Geocentric Coordinates"),
	X_New = 31210U UMETA(DisplayName = "X (New)"),
	Y_New = 31220U UMETA(DisplayName = "Y (New)"),
	Z_New = 31230U UMETA(DisplayName = "Z (New)"),
	Latitude = 31300U UMETA(DisplayName = "Latitude"),
	Longitude = 31400U UMETA(DisplayName = "Longitude"),
	LineofSight = 31500U UMETA(DisplayName = "Line of Sight"),
	X_AlsoNew = 31510U UMETA(DisplayName = "X (Also New)"),
	Y_AlsoNew = 31520U UMETA(DisplayName = "Y (Also New)"),
	Z_AlsoNew = 31530U UMETA(DisplayName = "Z (Also New)"),
	Altitude = 31600U UMETA(DisplayName = "Altitude"),
	DestinationLatitude = 31700U UMETA(DisplayName = "Destination Latitude"),
	DestinationLongitude = 31800U UMETA(DisplayName = "Destination Longitude"),
	DestinationAltitude = 31900U UMETA(DisplayName = "Destination Altitude"),
	Orientation = 32000U UMETA(DisplayName = "Orientation"),
	HullHeadingAngle = 32100U UMETA(DisplayName = "Hull Heading Angle"),
	HullPitchAngle = 32200U UMETA(DisplayName = "Hull Pitch Angle"),
	RollAngle = 32300U UMETA(DisplayName = "Roll Angle"),
	X_FinalNew = 32500U UMETA(DisplayName = "X (Final New)"),
	Y_FinalNew = 32600U UMETA(DisplayName = "Y (Final New)"),
	Z_FinalNew = 32700U UMETA(DisplayName = "Z (Final New)"),
	Appearance = 33000U UMETA(DisplayName = "Appearance"),
	AmbientLighting = 33100U UMETA(DisplayName = "Ambient Lighting"),
	Lights = 33101U UMETA(DisplayName = "Lights"),
	PaintScheme = 33200U UMETA(DisplayName = "Paint Scheme"),
	Smoke = 33300U UMETA(DisplayName = "Smoke"),
	TrailingEffects = 33400U UMETA(DisplayName = "Trailing Effects"),
	Flaming = 33500U UMETA(DisplayName = "Flaming"),
	Marking = 33600U UMETA(DisplayName = "Marking"),
	MinePlowsAttached = 33710U UMETA(DisplayName = "Mine Plows Attached"),
	MineRollersAttached = 33720U UMETA(DisplayName = "Mine Rollers Attached"),
	TankTurretAzimuth = 33730U UMETA(DisplayName = "Tank Turret Azimuth"),
	FailuresandMalfunctions = 34000U UMETA(DisplayName = "Failures and Malfunctions"),
	Age = 34100U UMETA(DisplayName = "Age"),
	Kilometers = 34110U UMETA(DisplayName = "Kilometers"),
	Damage = 35000U UMETA(DisplayName = "Damage"),
	Cause = 35050U UMETA(DisplayName = "Cause"),
	MobilityKill = 35100U UMETA(DisplayName = "Mobility Kill"),
	FirePowerKill = 35200U UMETA(DisplayName = "Fire-Power Kill"),
	PersonnelCasualties = 35300U UMETA(DisplayName = "Personnel Casualties"),
	Velocity = 36000U UMETA(DisplayName = "Velocity"),
	Xvelocity = 36100U UMETA(DisplayName = "X-velocity"),
	Yvelocity = 36200U UMETA(DisplayName = "Y-velocity"),
	Zvelocity = 36300U UMETA(DisplayName = "Z-velocity"),
	Speed_New = 36400U UMETA(DisplayName = "Speed (New)"),
	Acceleration = 37000U UMETA(DisplayName = "Acceleration"),
	Xacceleration = 37100U UMETA(DisplayName = "X-acceleration"),
	Yacceleration = 37200U UMETA(DisplayName = "Y-acceleration"),
	Zacceleration = 37300U UMETA(DisplayName = "Z-acceleration"),
	EngineStatus = 38100U UMETA(DisplayName = "Engine Status"),
	PrimaryTargetLinePTL = 39000U UMETA(DisplayName = "Primary Target Line (PTL)"),
	Exercise = 40000U UMETA(DisplayName = "Exercise"),
	ExerciseState = 40010U UMETA(DisplayName = "Exercise State"),
	Restart_Refresh = 40015U UMETA(DisplayName = "Restart/Refresh"),
	AFATDSFileName = 40020U UMETA(DisplayName = "AFATDS File Name"),
	TerrainDatabase = 41000U UMETA(DisplayName = "Terrain Database"),
	Missions = 42000U UMETA(DisplayName = "Missions"),
	MissionID = 42100U UMETA(DisplayName = "Mission ID"),
	MissionType = 42200U UMETA(DisplayName = "Mission Type"),
	MissionRequestTimeStamp = 42300U UMETA(DisplayName = "Mission Request Time Stamp"),
	ExerciseDescription = 43000U UMETA(DisplayName = "Exercise Description"),
	Name = 43100U UMETA(DisplayName = "Name"),
	Entities = 43200U UMETA(DisplayName = "Entities"),
	Version = 43300U UMETA(DisplayName = "Version"),
	GuiseMode = 43410U UMETA(DisplayName = "Guise Mode"),
	SimulationApplicationActiveStatus = 43420U UMETA(DisplayName = "Simulation Application Active Status"),
	SimulationApplicationRoleRecord = 43430U UMETA(DisplayName = "Simulation Application Role Record"),
	SimulationApplicationState = 43440U UMETA(DisplayName = "Simulation Application State"),
	VisualOutputMode = 44000U UMETA(DisplayName = "Visual Output Mode"),
	SimulationManagerRole = 44100U UMETA(DisplayName = "Simulation Manager Role"),
	SimulationManagerSiteID = 44110U UMETA(DisplayName = "Simulation Manager Site ID"),
	SimulationManagerApplic_ID = 44120U UMETA(DisplayName = "Simulation Manager Applic. ID"),
	SimulationManagerEntityID = 44130U UMETA(DisplayName = "Simulation Manager Entity ID"),
	SimulationManagerActiveStatus = 44140U UMETA(DisplayName = "Simulation Manager Active Status"),
	AfterActiveReviewRole = 44200U UMETA(DisplayName = "After Active Review Role"),
	AfterActiveReviewSiteID = 44210U UMETA(DisplayName = "After Active Review Site ID"),
	AfterActiveApplic_ID = 44220U UMETA(DisplayName = "After Active Applic. ID"),
	AfterActiveReviewEntityID = 44230U UMETA(DisplayName = "After Active Review Entity ID"),
	AfterActiveReviewActiveStatus = 44240U UMETA(DisplayName = "After Active Review Active Status"),
	ExerciseLoggerRole = 44300U UMETA(DisplayName = "Exercise Logger Role"),
	ExerciseLoggerSiteID = 44310U UMETA(DisplayName = "Exercise Logger Site ID"),
	ExerciseLoggerApplic_ID = 44320U UMETA(DisplayName = "Exercise Logger Applic. ID"),
	ExerciseEntityID = 44330U UMETA(DisplayName = "Exercise Entity ID"),
	ExerciseLoggerActiveStatus = 44340U UMETA(DisplayName = "Exercise Logger Active Status"),
	SyntheticEnvironmentManagerRole = 44400U UMETA(DisplayName = "Synthetic Environment Manager Role"),
	SyntheticEnvironmentManagerSiteID = 44410U UMETA(DisplayName = "Synthetic Environment Manager Site ID"),
	SyntheticEnvironmentManagerApplic_ID = 44420U UMETA(DisplayName = "Synthetic Environment Manager Applic. ID"),
	SyntheticEnvironmentManagerEntityID = 44430U UMETA(DisplayName = "Synthetic Environment Manager Entity ID"),
	SyntheticEnvironmentManagerActiveStatus = 44440U UMETA(DisplayName = "Synthetic Environment Manager Active Status"),
	SIMNETDISTranslatorRole = 44500U UMETA(DisplayName = "SIMNET-DIS Translator Role"),
	SIMNETDISTranslatorSiteID = 44510U UMETA(DisplayName = "SIMNET-DIS Translator Site ID"),
	SIMNETDISTranslatorApplic_ID = 44520U UMETA(DisplayName = "SIMNET-DIS Translator Applic. ID"),
	SIMNETDISTranslatorEntityID = 44530U UMETA(DisplayName = "SIMNET-DIS Translator Entity ID"),
	SIMNETDISTranslatorActiveStatus = 44540U UMETA(DisplayName = "SIMNET-DIS Translator Active Status"),
	ApplicationRate = 45000U UMETA(DisplayName = "Application Rate"),
	ApplicationTime = 45005U UMETA(DisplayName = "Application Time"),
	ApplicationTimestep = 45010U UMETA(DisplayName = "Application Timestep"),
	FeedbackTime = 45020U UMETA(DisplayName = "Feedback Time"),
	SimulationRate = 45030U UMETA(DisplayName = "Simulation Rate"),
	SimulationTime = 45040U UMETA(DisplayName = "Simulation Time"),
	SimulationTimestep = 45050U UMETA(DisplayName = "Simulation Timestep"),
	TimeInterval = 45060U UMETA(DisplayName = "Time Interval"),
	TimeLatency = 45070U UMETA(DisplayName = "Time Latency"),
	TimeScheme = 45080U UMETA(DisplayName = "Time Scheme"),
	ExerciseElapsedTime = 46000U UMETA(DisplayName = "Exercise Elapsed Time"),
	ElapsedTime = 46010U UMETA(DisplayName = "Elapsed Time"),
	Environment = 50000U UMETA(DisplayName = "Environment"),
	Weather = 51000U UMETA(DisplayName = "Weather"),
	WeatherCondition = 51010U UMETA(DisplayName = "Weather Condition"),
	ThermalCondition = 51100U UMETA(DisplayName = "Thermal Condition"),
	ThermalVisibility = 51110U UMETA(DisplayName = "Thermal Visibility"),
	ThermalVisibility_New = 51111U UMETA(DisplayName = "Thermal Visibility (New)"),
	Time = 52000U UMETA(DisplayName = "Time"),
	Time_New = 52001U UMETA(DisplayName = "Time (New)"),
	TimeofDay_Discrete = 52100U UMETA(DisplayName = "Time of Day, Discrete"),
	TimeofDay_Continuous = 52200U UMETA(DisplayName = "Time of Day, Continuous"),
	TimeMode = 52300U UMETA(DisplayName = "Time Mode"),
	TimeScene = 52305U UMETA(DisplayName = "Time Scene"),
	CurrentHour = 52310U UMETA(DisplayName = "Current Hour"),
	CurrentMinute = 52320U UMETA(DisplayName = "Current Minute"),
	CurrentSecond = 52330U UMETA(DisplayName = "Current Second"),
	Azimuth_New = 52340U UMETA(DisplayName = "Azimuth (New)"),
	MaximumElevation = 52350U UMETA(DisplayName = "Maximum Elevation"),
	TimeZone = 52360U UMETA(DisplayName = "Time Zone"),
	TimeRate = 52370U UMETA(DisplayName = "Time Rate"),
	SimSecondsSinceExerciseStart = 52380U UMETA(DisplayName = "The number of simulation seconds since the start of the exercise (simulation time)"),
	TimeSunriseEnabled = 52400U UMETA(DisplayName = "Time Sunrise Enabled"),
	SunriseHour = 52410U UMETA(DisplayName = "Sunrise Hour"),
	SunriseMinute = 52420U UMETA(DisplayName = "Sunrise Minute"),
	SunriseSecond = 52430U UMETA(DisplayName = "Sunrise Second"),
	SunriseAzimuth = 52440U UMETA(DisplayName = "Sunrise Azimuth"),
	TimeSunsetEnabled = 52500U UMETA(DisplayName = "Time Sunset Enabled"),
	SunsetHour = 52510U UMETA(DisplayName = "Sunset Hour"),
	SunsetHour_New = 52511U UMETA(DisplayName = "Sunset Hour (New)"),
	SunsetMinute = 52520U UMETA(DisplayName = "Sunset Minute"),
	SunsetSecond = 52530U UMETA(DisplayName = "Sunset Second"),
	Date = 52600U UMETA(DisplayName = "Date"),
	DateEuropean = 52601U UMETA(DisplayName = "Date (European)"),
	DateUS = 52602U UMETA(DisplayName = "Date (US)"),
	Month = 52610U UMETA(DisplayName = "Month"),
	Day = 52620U UMETA(DisplayName = "Day"),
	Year = 52630U UMETA(DisplayName = "Year"),
	Clouds = 53000U UMETA(DisplayName = "Clouds"),
	CloudLayerEnable = 53050U UMETA(DisplayName = "Cloud Layer Enable"),
	CloudLayerSelection = 53060U UMETA(DisplayName = "Cloud Layer Selection"),
	Visibility = 53100U UMETA(DisplayName = "Visibility"),
	BaseAltitude = 53200U UMETA(DisplayName = "Base Altitude"),
	BaseAltitude_New = 53250U UMETA(DisplayName = "Base Altitude (New)"),
	Ceiling = 53300U UMETA(DisplayName = "Ceiling"),
	Ceiling_New = 53350U UMETA(DisplayName = "Ceiling (New)"),
	Characteristics = 53400U UMETA(DisplayName = "Characteristics"),
	ConcentrationLength = 53410U UMETA(DisplayName = "Concentration Length"),
	Transmittance = 53420U UMETA(DisplayName = "Transmittance"),
	Radiance = 53430U UMETA(DisplayName = "Radiance"),
	Precipitation = 54000U UMETA(DisplayName = "Precipitation"),
	Rain = 54100U UMETA(DisplayName = "Rain"),
	Fog = 55000U UMETA(DisplayName = "Fog"),
	Visibility_New = 55100U UMETA(DisplayName = "Visibility (New)"),
	Visibility_AlsoNew = 55101U UMETA(DisplayName = "Visibility (Also New)"),
	Visibility_NewAsWell = 55105U UMETA(DisplayName = "Visibility (New As Well)"),
	Density = 55200U UMETA(DisplayName = "Density"),
	Base = 55300U UMETA(DisplayName = "Base"),
	ViewLayerfromabove_ = 55401U UMETA(DisplayName = "View Layer from above."),
	TransitionRange = 55410U UMETA(DisplayName = "Transition Range"),
	Bottom = 55420U UMETA(DisplayName = "Bottom"),
	Bottom_New = 55425U UMETA(DisplayName = "Bottom (New)"),
	Ceiling_AlsoNew = 55430U UMETA(DisplayName = "Ceiling (Also New)"),
	Ceiling_NewAsWell = 55435U UMETA(DisplayName = "Ceiling (New As Well)"),
	HeavenlyBodies = 56000U UMETA(DisplayName = "Heavenly Bodies"),
	Sun = 56100U UMETA(DisplayName = "Sun"),
	SunVisible = 56105U UMETA(DisplayName = "Sun Visible"),
	Position_New = 56110U UMETA(DisplayName = "Position (New)"),
	SunPositionElevation_Degrees = 56111U UMETA(DisplayName = "Sun Position Elevation, Degrees"),
	PositionAzimuth = 56120U UMETA(DisplayName = "Position Azimuth"),
	SunPositionAzimuth_Degrees = 56121U UMETA(DisplayName = "Sun Position Azimuth, Degrees"),
	PositionElevation = 56130U UMETA(DisplayName = "Position Elevation"),
	PositionIntensity = 56140U UMETA(DisplayName = "Position Intensity"),
	Moon = 56200U UMETA(DisplayName = "Moon"),
	MoonVisible = 56205U UMETA(DisplayName = "Moon Visible"),
	Position_AlsoNew = 56210U UMETA(DisplayName = "Position (Also New)"),
	PositionAzimuth_New = 56220U UMETA(DisplayName = "Position Azimuth (New)"),
	MoonPositionAzimuth_Degrees = 56221U UMETA(DisplayName = "Moon Position Azimuth, Degrees"),
	PositionElevation_New = 56230U UMETA(DisplayName = "Position Elevation (New)"),
	MoonPositionElevation_Degrees = 56231U UMETA(DisplayName = "Moon Position Elevation, Degrees"),
	PositionIntensity_New = 56240U UMETA(DisplayName = "Position Intensity (New)"),
	Horizon = 56310U UMETA(DisplayName = "Horizon"),
	HorizonAzimuth = 56320U UMETA(DisplayName = "Horizon Azimuth"),
	HorizonElevation = 56330U UMETA(DisplayName = "Horizon Elevation"),
	HorizonHeading = 56340U UMETA(DisplayName = "Horizon Heading"),
	HorizonIntensity = 56350U UMETA(DisplayName = "Horizon Intensity"),
	Humidity = 57200U UMETA(DisplayName = "Humidity"),
	Visibility_YetAnother = 57300U UMETA(DisplayName = "Visibility (Yet Another)"),
	Winds = 57400U UMETA(DisplayName = "Winds"),
	Speed = 57410U UMETA(DisplayName = "Speed"),
	WindSpeed_Knots = 57411U UMETA(DisplayName = "Wind Speed, Knots"),
	WindDirection = 57420U UMETA(DisplayName = "Wind Direction"),
	WindDirection_Degrees = 57421U UMETA(DisplayName = "Wind Direction, Degrees"),
	Rainsoak = 57500U UMETA(DisplayName = "Rainsoak"),
	TideSpeed = 57610U UMETA(DisplayName = "Tide Speed"),
	TideSpeed_Knots = 57611U UMETA(DisplayName = "Tide Speed, Knots"),
	TideDirection = 57620U UMETA(DisplayName = "Tide Direction"),
	TideDirection_Degrees = 57621U UMETA(DisplayName = "Tide Direction, Degrees"),
	Haze = 58000U UMETA(DisplayName = "Haze"),
	Visibility_AnotherNew = 58100U UMETA(DisplayName = "Visibility (Another New)"),
	Visibility_FinalNew = 58105U UMETA(DisplayName = "Visibility (Final New)"),
	Density_New = 58200U UMETA(DisplayName = "Density_New"),
	Ceiling_AnotherNew = 58430U UMETA(DisplayName = "Ceiling (Another New)"),
	Ceiling_FinalNew = 58435U UMETA(DisplayName = "Ceiling (Final New)"),
	ContaminantsandObscurants = 59000U UMETA(DisplayName = "Contaminants and Obscurants"),
	Contaminant_ObscurantType = 59100U UMETA(DisplayName = "Contaminant/Obscurant Type"),
	Persistence = 59110U UMETA(DisplayName = "Persistence"),
	ChemicalDosage = 59115U UMETA(DisplayName = "Chemical Dosage"),
	ChemicalAirConcentration = 59120U UMETA(DisplayName = "Chemical Air Concentration"),
	ChemicalGroundDeposition = 59125U UMETA(DisplayName = "Chemical Ground Deposition"),
	ChemicalMaximumGroundDeposition = 59130U UMETA(DisplayName = "Chemical Maximum Ground Deposition"),
	ChemicalDosageThreshold = 59135U UMETA(DisplayName = "Chemical Dosage Threshold"),
	BiologicalDosage = 59140U UMETA(DisplayName = "Biological Dosage"),
	BiologicalAirConcentration = 59145U UMETA(DisplayName = "Biological Air Concentration"),
	BiologicalDosageThreshold = 59150U UMETA(DisplayName = "Biological Dosage Threshold"),
	BiologicalBinnedParticleCount = 59155U UMETA(DisplayName = "Biological Binned Particle Count"),
	RadiologicalDosage = 59160U UMETA(DisplayName = "Radiological Dosage"),
	Communications = 60000U UMETA(DisplayName = "Communications"),
	ChannelType = 61100U UMETA(DisplayName = "Channel Type"),
	ChannelType_New = 61101U UMETA(DisplayName = "Channel Type (New)"),
	ChannelIdentification = 61200U UMETA(DisplayName = "Channel Identification"),
	AlphaIdentification = 61300U UMETA(DisplayName = "Alpha Identification"),
	RadioIdentification = 61400U UMETA(DisplayName = "Radio Identification"),
	LandLineIdentification = 61500U UMETA(DisplayName = "Land Line Identification"),
	IntercomIdentification = 61600U UMETA(DisplayName = "Intercom Identification"),
	GroupNetworkChannelNumber = 61700U UMETA(DisplayName = "Group Network Channel Number"),
	RadioCommunicationsStatus = 62100U UMETA(DisplayName = "Radio Communications Status"),
	StationaryRadioTransmittersDefaultTime = 62200U UMETA(DisplayName = "Stationary Radio Transmitters Default Time"),
	MovingRadioTransmittersDefaultTime = 62300U UMETA(DisplayName = "Moving Radio Transmitters Default Time"),
	StationaryRadioSignalsDefaultTime = 62400U UMETA(DisplayName = "Stationary Radio Signals Default Time"),
	MovingRadioSignalDefaultTime = 62500U UMETA(DisplayName = "Moving Radio Signal Default Time"),
	RadioInitializationTransecSecurityKey = 63101U UMETA(DisplayName = "Radio Initialization Transec Security Key"),
	RadioInitializationInternalNoiseLevel = 63102U UMETA(DisplayName = "Radio Initialization Internal Noise Level"),
	RadioInitializationSquelchThreshold = 63103U UMETA(DisplayName = "Radio Initialization Squelch Threshold"),
	RadioInitializationAntennaLocation = 63104U UMETA(DisplayName = "Radio Initialization Antenna Location"),
	RadioInitializationAntennaPatternType = 63105U UMETA(DisplayName = "Radio Initialization Antenna Pattern Type"),
	RadioInitializationAntennaPatternLength = 63106U UMETA(DisplayName = "Radio Initialization Antenna Pattern Length"),
	RadioInitializationBeamDefinition = 63107U UMETA(DisplayName = "Radio Initialization Beam Definition"),
	RadioInitializationTransmitHeartbeatTime = 63108U UMETA(DisplayName = "Radio Initialization Transmit Heartbeat Time"),
	RadioInitializationTransmitDistanceThresholdVariableRecord = 63109U UMETA(DisplayName = "Radio Initialization Transmit Distance Threshold Variable Record"),
	RadioChannelInitializationLockoutID = 63110U UMETA(DisplayName = "Radio Channel Initialization Lockout ID"),
	RadioChannelInitializationHopsetID = 63111U UMETA(DisplayName = "Radio Channel Initialization Hopset ID"),
	RadioChannelInitializationPresetFrequency = 63112U UMETA(DisplayName = "Radio Channel Initialization Preset Frequency"),
	RadioChannelInitializationFrequencySyncTime = 63113U UMETA(DisplayName = "Radio Channel Initialization Frequency Sync Time"),
	RadioChannelInitializationComsecKey = 63114U UMETA(DisplayName = "Radio Channel Initialization Comsec Key"),
	RadioChannelInitializationAlpha = 63115U UMETA(DisplayName = "Radio Channel Initialization Alpha"),
	AlgorithmParameters = 70000U UMETA(DisplayName = "Algorithm Parameters"),
	DeadReckoningAlgorithmDRA = 71000U UMETA(DisplayName = "Dead Reckoning Algorithm (DRA)"),
	DRALocationThreshold = 71100U UMETA(DisplayName = "DRA Location Threshold"),
	DRAOrientationThreshold = 71200U UMETA(DisplayName = "DRA Orientation Threshold"),
	DRATimeThreshold = 71300U UMETA(DisplayName = "DRA Time Threshold"),
	SimulationManagementParameters = 72000U UMETA(DisplayName = "Simulation Management Parameters"),
	CheckpointInterval = 72100U UMETA(DisplayName = "Checkpoint Interval"),
	TransmitterTimeThreshold = 72600U UMETA(DisplayName = "Transmitter Time Threshold"),
	ReceiverTimeThreshold = 72700U UMETA(DisplayName = "Receiver Time Threshold"),
	InteroperabilityMode = 73000U UMETA(DisplayName = "Interoperability Mode"),
	SIMNETDataCollection = 74000U UMETA(DisplayName = "SIMNET Data Collection"),
	EventID = 75000U UMETA(DisplayName = "Event ID"),
	SourceSiteID = 75100U UMETA(DisplayName = "Source Site ID"),
	SourceHostID = 75200U UMETA(DisplayName = "Source Host ID"),
	ArticulatedParts = 90000U UMETA(DisplayName = "Articulated Parts"),
	PartID = 90050U UMETA(DisplayName = "Part ID"),
	Index = 90070U UMETA(DisplayName = "Index [UID 55]"),
	Position_NewAsWell = 90100U UMETA(DisplayName = "Position (New As Well)"),
	PositionRate = 90200U UMETA(DisplayName = "Position Rate"),
	Extension = 90300U UMETA(DisplayName = "Extension"),
	ExtensionRate = 90400U UMETA(DisplayName = "Extension Rate"),
	X = 90500U UMETA(DisplayName = "X"),
	Xrate = 90600U UMETA(DisplayName = "X-rate"),
	Y = 90700U UMETA(DisplayName = "Y"),
	Yrate = 90800U UMETA(DisplayName = "Y-rate"),
	Z = 90900U UMETA(DisplayName = "Z"),
	Zrate = 91000U UMETA(DisplayName = "Z-rate"),
	Azimuth = 91100U UMETA(DisplayName = "Azimuth"),
	AzimuthRate = 91200U UMETA(DisplayName = "Azimuth Rate"),
	Elevation = 91300U UMETA(DisplayName = "Elevation"),
	ElevationRate = 91400U UMETA(DisplayName = "Elevation Rate"),
	Rotation = 91500U UMETA(DisplayName = "Rotation"),
	RotationRate = 91600U UMETA(DisplayName = "Rotation Rate"),
	DRAAngularXVelocity = 100001U UMETA(DisplayName = "DRA Angular X-Velocity"),
	DRAAngularYVelocity = 100002U UMETA(DisplayName = "DRA Angular Y-Velocity"),
	DRAAngularZVelocity = 100003U UMETA(DisplayName = "DRA Angular Z-Velocity"),
	Appearance_TrailingEffects = 100004U UMETA(DisplayName = "Appearance, Trailing Effects"),
	Appearance_Hatch = 100005U UMETA(DisplayName = "Appearance, Hatch"),
	Appearance_CharacterSet = 100008U UMETA(DisplayName = "Appearance, Character Set"),
	Capability_AmmunitionSupplier = 100010U UMETA(DisplayName = "Capability, Ammunition Supplier"),
	Capability_MiscellaneousSupplier = 100011U UMETA(DisplayName = "Capability, Miscellaneous Supplier"),
	Capability_RepairProvider = 100012U UMETA(DisplayName = "Capability, Repair Provider"),
	ArticulationParameter = 100014U UMETA(DisplayName = "Articulation Parameter"),
	ArticulationParameterType = 100047U UMETA(DisplayName = "Articulation Parameter Type"),
	ArticulationParameterValue = 100048U UMETA(DisplayName = "Articulation Parameter Value"),
	TimeofDayScene = 100058U UMETA(DisplayName = "Time of Day-Scene"),
	LatitudeNorthLocationofweathercell = 100061U UMETA(DisplayName = "Latitude-North (Location of weather cell)"),
	LongitudeEastLocationofweathercell = 100063U UMETA(DisplayName = "Longitude-East (Location of weather cell)"),
	TacticalDriverStatus = 100068U UMETA(DisplayName = "Tactical Driver Status"),
	SonarSystemStatus = 100100U UMETA(DisplayName = "Sonar System Status"),
	Upperlatitude = 100161U UMETA(DisplayName = "Upper latitude"),
	LatitudeSouthLocationofweathercell = 100162U UMETA(DisplayName = "Latitude-South (Location of weather cell)"),
	Westernlongitude = 100163U UMETA(DisplayName = "Western longitude"),
	LongitudeWestlocationofweathercell = 100164U UMETA(DisplayName = "Longitude-West (location of weather cell)"),
	Accomplishedaccept = 100160U UMETA(DisplayName = "Accomplished accept"),
	CDROMNumberDiskIDforterrain = 100165U UMETA(DisplayName = "CD ROM Number (Disk ID for terrain)"),
	DTEDdiskID = 100166U UMETA(DisplayName = "DTED disk ID"),
	Altitude_New = 100167U UMETA(DisplayName = "Altitude (New)"),
	TacticalSystemStatus = 100169U UMETA(DisplayName = "Tactical System Status"),
	JTIDSStatus = 100170U UMETA(DisplayName = "JTIDS Status"),
	TADILJStatus = 100171U UMETA(DisplayName = "TADIL-J Status"),
	DSDDStatus = 100172U UMETA(DisplayName = "DSDD Status"),
	WeaponSystemStatus = 100200U UMETA(DisplayName = "Weapon System Status"),
	Subsystemstatus = 100205U UMETA(DisplayName = "Subsystem status"),
	Numberofinterceptorsfired = 100206U UMETA(DisplayName = "Number of interceptors fired"),
	Numberofinterceptordetonations = 100207U UMETA(DisplayName = "Number of interceptor detonations"),
	Numberofmessagebuffersdropped = 100208U UMETA(DisplayName = "Number of message buffers dropped"),
	Satellitesensorbackgroundyear_day = 100213U UMETA(DisplayName = "Satellite sensor background (year, day)"),
	Satellitesensorbackgroundhour_minute = 100214U UMETA(DisplayName = "Satellite sensor background (hour, minute)"),
	ScriptNumber = 100218U UMETA(DisplayName = "Script Number"),
	Entity_Track_UpdateData = 100300U UMETA(DisplayName = "Entity/Track/Update Data"),
	Local_ForceTraining = 100400U UMETA(DisplayName = "Local/Force Training"),
	Entity_TrackIdentityData = 100500U UMETA(DisplayName = "Entity/Track Identity Data"),
	EntityforTrackEvent = 100510U UMETA(DisplayName = "Entity for Track Event"),
	IFFFriendFoestatus = 100520U UMETA(DisplayName = "IFF (Friend-Foe) status"),
	EngagementData = 100600U UMETA(DisplayName = "Engagement Data"),
	TargetLatitude = 100610U UMETA(DisplayName = "Target Latitude"),
	TargetLongitude = 100620U UMETA(DisplayName = "Target Longitude"),
	AreaofInterestGroundImpactCircleCenterLatitude = 100631U UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Center Latitude"),
	AreaofInterestGroundImpactCircleCenterLongitude = 100632U UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Center Longitude"),
	AreaofInterestGroundImpactCircleRadius = 100633U UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Radius"),
	AreaofInterestType = 100634U UMETA(DisplayName = "Area of Interest Type"),
	TargetAggregateID = 100640U UMETA(DisplayName = "Target Aggregate ID"),
	GICIdentificationNumber = 100650U UMETA(DisplayName = "GIC Identification Number"),
	EstimatedTimeofFlighttoTBMImpact = 100660U UMETA(DisplayName = "Estimated Time of Flight to TBM Impact"),
	EstimatedInterceptTime = 100661U UMETA(DisplayName = "Estimated Intercept Time"),
	EstimatedTimeofFlighttoNextWaypoint = 100662U UMETA(DisplayName = "Estimated Time of Flight to Next Waypoint"),
	Entity_TrackEquipmentData = 100700U UMETA(DisplayName = "Entity/Track Equipment Data"),
	Emission_EWData = 100800U UMETA(DisplayName = "Emission/EW Data"),
	AppearanceData = 100900U UMETA(DisplayName = "Appearance Data"),
	Command_OrderData = 101000U UMETA(DisplayName = "Command/Order Data"),
	EnvironmentalData = 101100U UMETA(DisplayName = "Environmental Data"),
	SignificantEventData = 101200U UMETA(DisplayName = "Significant Event Data"),
	OperatorActionData = 101300U UMETA(DisplayName = "Operator Action Data"),
	ADAEngagementMode = 101310U UMETA(DisplayName = "ADA Engagement Mode"),
	ADAShootingStatus = 101320U UMETA(DisplayName = "ADA Shooting Status"),
	ADAMode = 101321U UMETA(DisplayName = "ADA Mode"),
	ADARadarStatus = 101330U UMETA(DisplayName = "ADA Radar Status"),
	ShootCommand = 101340U UMETA(DisplayName = "Shoot Command"),
	ADAWeaponStatus = 101350U UMETA(DisplayName = "ADA Weapon Status"),
	ADAFiringDisciple = 101360U UMETA(DisplayName = "ADA Firing Disciple"),
	OrderStatus = 101370U UMETA(DisplayName = "Order Status"),
	TimeSynchronization = 101400U UMETA(DisplayName = "Time Synchronization"),
	TomahawkData = 101500U UMETA(DisplayName = "Tomahawk Data"),
	NumberofDetonations = 102100U UMETA(DisplayName = "Number of Detonations"),
	NumberofIntercepts = 102200U UMETA(DisplayName = "Number of Intercepts"),
	OBTControlMT201 = 200201U UMETA(DisplayName = "OBT Control MT-201"),
	SensorDataMT202 = 200202U UMETA(DisplayName = "Sensor Data MT-202"),
	EnvironmentalDataMT203 = 200203U UMETA(DisplayName = "Environmental Data MT-203"),
	OwnshipDataMT204 = 200204U UMETA(DisplayName = "Ownship Data MT-204"),
	AcousticContactDataMT205 = 200205U UMETA(DisplayName = "Acoustic Contact Data MT-205"),
	SonobuoyDataMT207 = 200207U UMETA(DisplayName = "Sonobuoy Data MT-207"),
	SonobuoyContactDataMT210 = 200210U UMETA(DisplayName = "Sonobuoy Contact Data MT-210"),
	HeloControlMT211 = 200211U UMETA(DisplayName = "Helo Control MT-211"),
	ESMControlData = 200213U UMETA(DisplayName = "ESM Control Data"),
	ESMContactDataMT214 = 200214U UMETA(DisplayName = "ESM Contact Data MT-214"),
	ESMEmitterDataMT215 = 200215U UMETA(DisplayName = "ESM Emitter Data MT-215"),
	WeaponDefinitionDataMT217 = 200216U UMETA(DisplayName = "Weapon Definition Data MT-217"),
	WeaponPresetDataMT217 = 200217U UMETA(DisplayName = "Weapon Preset Data MT-217"),
	OBTControlMT301 = 200301U UMETA(DisplayName = "OBT Control MT-301"),
	SensorDataMT302 = 200302U UMETA(DisplayName = "Sensor Data MT-302"),
	EnvironmentalDataMT303m = 200303U UMETA(DisplayName = "Environmental Data MT-303m"),
	OwnshipDataMT304 = 200304U UMETA(DisplayName = "Ownship Data MT-304"),
	AcousticContactDataMT305 = 200305U UMETA(DisplayName = "Acoustic Contact Data MT-305"),
	SonobuoyDataMT307 = 200307U UMETA(DisplayName = "Sonobuoy Data MT-307"),
	SonobuoyContactDataMT310 = 200310U UMETA(DisplayName = "Sonobuoy Contact Data MT-310"),
	HeloScenario_EquipmentStatus = 200311U UMETA(DisplayName = "Helo Scenario / Equipment Status"),
	ESMControlDataMT313 = 200313U UMETA(DisplayName = "ESM Control Data MT-313"),
	ESMContactDataMT314 = 200314U UMETA(DisplayName = "ESM Contact Data MT-314"),
	ESMEmitterDataMT315 = 200315U UMETA(DisplayName = "ESM Emitter Data MT-315"),
	WeaponDefinitionDataMT316 = 200316U UMETA(DisplayName = "Weapon Definition Data MT-316"),
	WeaponPresetDataMT317 = 200317U UMETA(DisplayName = "Weapon Preset Data MT-317"),
	Pairing_AssociationeMT56 = 200400U UMETA(DisplayName = "Pairing/Association (eMT-56)"),
	PointereMT57 = 200401U UMETA(DisplayName = "Pointer (eMT-57)"),
	ReportingResponsibilityeMT58 = 200402U UMETA(DisplayName = "Reporting Responsibility (eMT-58)"),
	TrackNumbereMT59 = 200403U UMETA(DisplayName = "Track Number (eMT-59)"),
	IDforLink11ReportingeMT60 = 200404U UMETA(DisplayName = "ID for Link-11 Reporting (eMT-60)"),
	RemoteTrackeMT62 = 200405U UMETA(DisplayName = "Remote Track (eMT-62)"),
	Link11ErrorRateeMT63 = 200406U UMETA(DisplayName = "Link-11 Error Rate (eMT-63)"),
	TrackQualityeMT64 = 200407U UMETA(DisplayName = "Track Quality (eMT-64)"),
	GridlockeMT65 = 200408U UMETA(DisplayName = "Gridlock (eMT-65)"),
	KilleMT66 = 200409U UMETA(DisplayName = "Kill (eMT-66)"),
	TrackIDChange_ResolutioneMT68 = 200410U UMETA(DisplayName = "Track ID Change / Resolution (eMT-68)"),
	WeaponsStatuseMT69 = 200411U UMETA(DisplayName = "Weapons Status (eMT-69)"),
	Link11OperatoreMT70 = 200412U UMETA(DisplayName = "Link-11 Operator (eMT-70)"),
	ForceTrainingTransmiteMT71 = 200413U UMETA(DisplayName = "Force Training Transmit (eMT-71)"),
	ForceTrainingReceiveeMT72 = 200414U UMETA(DisplayName = "Force Training Receive (eMT-72)"),
	InterceptorAmplificationeMT75 = 200415U UMETA(DisplayName = "Interceptor Amplification (eMT-75)"),
	ConsumableseMT78 = 200416U UMETA(DisplayName = "Consumables (eMT-78)"),
	Link11LocalTrackQualityeMT95 = 200417U UMETA(DisplayName = "Link-11 Local Track Quality (eMT-95)"),
	DLRPeMT19 = 200418U UMETA(DisplayName = "DLRP (eMT-19)"),
	ForceOrdereMT52 = 200419U UMETA(DisplayName = "Force Order (eMT-52)"),
	Wilco_CantcoeMT53 = 200420U UMETA(DisplayName = "Wilco / Cantco (eMT-53)"),
	EMCBearingeMT54 = 200421U UMETA(DisplayName = "EMC Bearing (eMT-54)"),
	ChangeTrackEligibilityeMT55 = 200422U UMETA(DisplayName = "Change Track Eligibility (eMT-55)"),
	LandMassReferencePoint = 200423U UMETA(DisplayName = "Land Mass Reference Point"),
	SystemReferencePoint = 200424U UMETA(DisplayName = "System Reference Point"),
	PUAmplification = 200425U UMETA(DisplayName = "PU Amplification"),
	Set_Drift = 200426U UMETA(DisplayName = "Set/Drift"),
	BeginInitializationMT1 = 200427U UMETA(DisplayName = "Begin Initialization (MT-1)"),
	StatusandControlMT3 = 200428U UMETA(DisplayName = "Status and Control (MT-3)"),
	ScintillationChangeMT39 = 200429U UMETA(DisplayName = "Scintillation Change (MT-39)"),
	Link11IDControlMT61 = 200430U UMETA(DisplayName = "Link 11 ID Control (MT-61)"),
	PUGuardList = 200431U UMETA(DisplayName = "PU Guard List"),
	WindsAloftMT14 = 200432U UMETA(DisplayName = "Winds Aloft (MT-14)"),
	SurfaceWindsMT15 = 200433U UMETA(DisplayName = "Surface Winds (MT-15)"),
	SeaStateMT17 = 200434U UMETA(DisplayName = "Sea State (MT-17)"),
	MagneticVariationMT37 = 200435U UMETA(DisplayName = "Magnetic Variation (MT-37)"),
	TrackEligibilityMT29 = 200436U UMETA(DisplayName = "Track Eligibility (MT-29)"),
	TrainingTrackNotification = 200437U UMETA(DisplayName = "Training Track Notification"),
	TacanDataMT32 = 200501U UMETA(DisplayName = "Tacan Data (MT-32)"),
	InterceptorAmplificationMT75 = 200502U UMETA(DisplayName = "Interceptor Amplification (MT-75)"),
	TacanAssignmentMT76 = 200503U UMETA(DisplayName = "Tacan Assignment (MT-76)"),
	AutopilotStatusMT77 = 200504U UMETA(DisplayName = "Autopilot Status (MT-77)"),
	ConsumablesMT78 = 200505U UMETA(DisplayName = "Consumables (MT-78)"),
	DownlinkMT79 = 200506U UMETA(DisplayName = "Downlink (MT-79)"),
	TINReportMT80 = 200507U UMETA(DisplayName = "TIN Report (MT-80)"),
	SpecialPointControlMT81 = 200508U UMETA(DisplayName = "Special Point Control (MT-81)"),
	ControlDiscretesMT82 = 200509U UMETA(DisplayName = "Control Discretes (MT-82)"),
	RequestTargetDiscretesMT83 = 200510U UMETA(DisplayName = "Request Target Discretes(MT-83)"),
	TargetDiscretesMT84 = 200511U UMETA(DisplayName = "Target Discretes (MT-84)"),
	ReplyDiscretesMT85 = 200512U UMETA(DisplayName = "Reply Discretes (MT-85)"),
	CommandManeuversMT86 = 200513U UMETA(DisplayName = "Command Maneuvers (MT-86)"),
	TargetDataMT87 = 200514U UMETA(DisplayName = "Target Data (MT-87)"),
	TargetPointerMT88 = 200515U UMETA(DisplayName = "Target Pointer (MT-88)"),
	InterceptDataMT89 = 200516U UMETA(DisplayName = "Intercept Data (MT-89)"),
	DecrementMissileInventoryMT90 = 200517U UMETA(DisplayName = "Decrement Missile Inventory (MT-90)"),
	Link4AAlertMT91 = 200518U UMETA(DisplayName = "Link-4A Alert (MT-91)"),
	StrikeControlMT92 = 200519U UMETA(DisplayName = "Strike Control (MT-92)"),
	SpeedChangeMT25 = 200521U UMETA(DisplayName = "Speed Change (MT-25)"),
	CourseChangeMT26 = 200522U UMETA(DisplayName = "Course Change (MT-26)"),
	AltitudeChangeMT27 = 200523U UMETA(DisplayName = "Altitude Change (MT-27)"),
	ACLSAN_SPN46Status = 200524U UMETA(DisplayName = "ACLS AN/SPN-46 Status"),
	ACLSAircraftReport = 200525U UMETA(DisplayName = "ACLS Aircraft Report"),
	SPS67RadarOperatorFunctions = 200600U UMETA(DisplayName = "SPS-67 Radar Operator Functions"),
	SPS55RadarOperatorFunctions = 200601U UMETA(DisplayName = "SPS-55 Radar Operator Functions"),
	SPQ9ARadarOperatorFunctions = 200602U UMETA(DisplayName = "SPQ-9A Radar Operator Functions"),
	SPS49RadarOperatorFunctions = 200603U UMETA(DisplayName = "SPS-49 Radar Operator Functions"),
	MK23RadarOperatorFunctions = 200604U UMETA(DisplayName = "MK-23 Radar Operator Functions"),
	SPS48RadarOperatorFunctions = 200605U UMETA(DisplayName = "SPS-48 Radar Operator Functions"),
	SPS40RadarOperatorFunctions = 200606U UMETA(DisplayName = "SPS-40 Radar Operator Functions"),
	MK95RadarOperatorFunctions = 200607U UMETA(DisplayName = "MK-95 Radar Operator Functions"),
	Kill_NoKill = 200608U UMETA(DisplayName = "Kill/No Kill"),
	CMTpc = 200609U UMETA(DisplayName = "CMT pc"),
	CMC4AirGlobalData = 200610U UMETA(DisplayName = "CMC4AirGlobalData"),
	CMC4GlobalData = 200611U UMETA(DisplayName = "CMC4GlobalData"),
	LINKSIM_COMMENT_PDU = 200612U UMETA(DisplayName = "LINKSIM_COMMENT_PDU"),
	NSSTOwnshipControl = 200613U UMETA(DisplayName = "NSST Ownship Control"),
	Other = 240000U UMETA(DisplayName = "Other"),
	MassOfTheVehicle = 240001U UMETA(DisplayName = "Mass Of The Vehicle"),
	ForceID_New = 240002U UMETA(DisplayName = "Force ID (New)"),
	EntityTypeKind = 240003U UMETA(DisplayName = "Entity Type Kind"),
	EntityTypeDomain = 240004U UMETA(DisplayName = "Entity Type Domain"),
	EntityTypeCountry = 240005U UMETA(DisplayName = "Entity Type Country"),
	EntityTypeCategory = 240006U UMETA(DisplayName = "Entity Type Category"),
	EntityTypeSubCategory = 240007U UMETA(DisplayName = "Entity Type Sub Category"),
	EntityTypeSpecific = 240008U UMETA(DisplayName = "Entity Type Specific"),
	EntityTypeExtra = 240009U UMETA(DisplayName = "Entity Type Extra"),
	AlternativeEntityTypeKind = 240010U UMETA(DisplayName = "Alternative Entity Type Kind"),
	AlternativeEntityTypeDomain = 240011U UMETA(DisplayName = "Alternative Entity Type Domain"),
	AlternativeEntityTypeCountry = 240012U UMETA(DisplayName = "Alternative Entity Type Country"),
	AlternativeEntityTypeCategory = 240013U UMETA(DisplayName = "Alternative Entity Type Category"),
	AlternativeEntityTypeSubCategory = 240014U UMETA(DisplayName = "Alternative Entity Type Sub Category"),
	AlternativeEntityTypeSpecific = 240015U UMETA(DisplayName = "Alternative Entity Type Specific"),
	AlternativeEntityTypeExtra = 240016U UMETA(DisplayName = "Alternative Entity Type Extra"),
	EntityLocationX = 240017U UMETA(DisplayName = "Entity Location X"),
	EntityLocationY = 240018U UMETA(DisplayName = "Entity Location Y"),
	EntityLocationZ = 240019U UMETA(DisplayName = "Entity Location Z"),
	EntityLinearVelocityX = 240020U UMETA(DisplayName = "Entity Linear Velocity X"),
	EntityLinearVelocityY = 240021U UMETA(DisplayName = "Entity Linear Velocity Y"),
	EntityLinearVelocityZ = 240022U UMETA(DisplayName = "Entity Linear Velocity Z"),
	EntityOrientationPsi = 240023U UMETA(DisplayName = "Entity Orientation Psi"),
	EntityOrientationTheta = 240024U UMETA(DisplayName = "Entity Orientation Theta"),
	EntityOrientationPhi = 240025U UMETA(DisplayName = "Entity Orientation Phi"),
	DeadReckoningAlgorithm = 240026U UMETA(DisplayName = "Dead Reckoning Algorithm"),
	DeadReckoningLinearAccelerationX = 240027U UMETA(DisplayName = "Dead Reckoning Linear Acceleration X"),
	DeadReckoningLinearAccelerationY = 240028U UMETA(DisplayName = "Dead Reckoning Linear Acceleration Y"),
	DeadReckoningLinearAccelerationZ = 240029U UMETA(DisplayName = "Dead Reckoning Linear Acceleration Z"),
	DeadReckoningAngularVelocityX = 240030U UMETA(DisplayName = "Dead Reckoning Angular Velocity X"),
	DeadReckoningAngularVelocityY = 240031U UMETA(DisplayName = "Dead Reckoning Angular Velocity Y"),
	DeadReckoningAngularVelocityZ = 240032U UMETA(DisplayName = "Dead Reckoning Angular Velocity Z"),
	EntityAppearance = 240033U UMETA(DisplayName = "Entity Appearance"),
	EntityMarkingCharacterSet = 240034U UMETA(DisplayName = "Entity Marking Character Set"),
	EntityMarking11Bytes = 240035U UMETA(DisplayName = "Entity Marking 11 Bytes"),
	Capability = 240036U UMETA(DisplayName = "Capability"),
	NumberArticulationParameters = 240037U UMETA(DisplayName = "Number Articulation Parameters"),
	ArticulationParameterID = 240038U UMETA(DisplayName = "Articulation Parameter ID"),
	ArticulationParameterType_New = 240039U UMETA(DisplayName = "Articulation Parameter Type (New)"),
	ArticulationParameterValue_New = 240040U UMETA(DisplayName = "Articulation Parameter Value (New)"),
	TypeOfStores = 240041U UMETA(DisplayName = "Type Of Stores"),
	QuantityOfStores = 240042U UMETA(DisplayName = "Quantity Of Stores"),
	FuelQuantity = 240043U UMETA(DisplayName = "Fuel Quantity"),
	RadarSystemStatus = 240044U UMETA(DisplayName = "Radar System Status"),
	RadioCommunicationSystemStatus = 240045U UMETA(DisplayName = "Radio Communication System Status"),
	DefaultTimeForRadioTransmissionForStationaryTransmitters = 240046U UMETA(DisplayName = "Default Time For Radio Transmission For Stationary Transmitters"),
	DefaultTimeForRadioTransmissionForMovingTransmitters = 240047U UMETA(DisplayName = "Default Time For Radio Transmission For Moving Transmitters"),
	BodyPartDamagedRatio = 240048U UMETA(DisplayName = "Body Part Damaged Ratio"),
	NameOfTheTerrainDatabaseFile = 240049U UMETA(DisplayName = "Name Of The Terrain Database File"),
	NameOfLocalFile = 240050U UMETA(DisplayName = "Name Of Local File"),
	AimpointBearing = 240051U UMETA(DisplayName = "Aimpoint Bearing"),
	AimpointElevation = 240052U UMETA(DisplayName = "Aimpoint Elevation"),
	AimpointRange = 240053U UMETA(DisplayName = "Aimpoint Range"),
	AirSpeed = 240054U UMETA(DisplayName = "Air Speed"),
	Altitude_AlsoNew = 240055U UMETA(DisplayName = "Altitude (Also New)"),
	ApplicationStatus = 240056U UMETA(DisplayName = "Application Status"),
	AutoIff = 240057U UMETA(DisplayName = "Auto Iff"),
	BeaconDelay = 240058U UMETA(DisplayName = "Beacon Delay"),
	BingoFuelSetting = 240059U UMETA(DisplayName = "Bingo Fuel Setting"),
	CloudBottom = 240060U UMETA(DisplayName = "Cloud Bottom"),
	CloudTop = 240061U UMETA(DisplayName = "Cloud Top"),
	Direction = 240062U UMETA(DisplayName = "Direction"),
	EndAction = 240063U UMETA(DisplayName = "End Action"),
	Frequency = 240064U UMETA(DisplayName = "Frequency"),
	Freeze = 240065U UMETA(DisplayName = "Freeze"),
	Heading = 240066U UMETA(DisplayName = "Heading"),
	Identification_New = 240067U UMETA(DisplayName = "Identification (New)"),
	InitialPointData = 240068U UMETA(DisplayName = "Initial Point Data"),
	Latitude_New = 240069U UMETA(DisplayName = "Latitude (New)"),
	Lights_New = 240070U UMETA(DisplayName = "Lights (New)"),
	Linear = 240071U UMETA(DisplayName = "Linear"),
	Longitude_New = 240072U UMETA(DisplayName = "Longitude (New)"),
	LowAltitude = 240073U UMETA(DisplayName = "Low Altitude"),
	MfdFormats = 240074U UMETA(DisplayName = "Mfd Formats"),
	Nctr = 240075U UMETA(DisplayName = "Nctr"),
	NumberProjectiles = 240076U UMETA(DisplayName = "Number Projectiles"),
	OperationCode = 240077U UMETA(DisplayName = "Operation Code"),
	Pitch = 240078U UMETA(DisplayName = "Pitch"),
	Profiles = 240079U UMETA(DisplayName = "Profiles"),
	Quantity_AlsoNew = 240080U UMETA(DisplayName = "Quantity (Also New)"),
	RadarModes = 240081U UMETA(DisplayName = "Radar Modes"),
	RadarSearchVolume = 240082U UMETA(DisplayName = "Radar Search Volume"),
	Roll = 240083U UMETA(DisplayName = "Roll"),
	Rotation_New = 240084U UMETA(DisplayName = "Rotation (New)"),
	ScaleFactorX = 240085U UMETA(DisplayName = "Scale Factor X"),
	ScaleFactorY = 240086U UMETA(DisplayName = "Scale Factor Y"),
	Shields = 240087U UMETA(DisplayName = "Shields"),
	Steerpoint = 240088U UMETA(DisplayName = "Steerpoint"),
	Spare1 = 240089U UMETA(DisplayName = "Spare1"),
	Spare2 = 240090U UMETA(DisplayName = "Spare2"),
	Team = 240091U UMETA(DisplayName = "Team"),
	Text = 240092U UMETA(DisplayName = "Text"),
	TimeOfDay = 240093U UMETA(DisplayName = "Time Of Day"),
	TrailFlag = 240094U UMETA(DisplayName = "Trail Flag"),
	TrailSize = 240095U UMETA(DisplayName = "Trail Size"),
	TypeOfProjectile = 240096U UMETA(DisplayName = "Type Of Projectile"),
	TypeOfTarget = 240097U UMETA(DisplayName = "Type Of Target"),
	TypeOfThreat = 240098U UMETA(DisplayName = "Type Of Threat"),
	UhfFrequency = 240099U UMETA(DisplayName = "Uhf Frequency"),
	UtmAltitude = 240100U UMETA(DisplayName = "Utm Altitude"),
	UtmLatitude = 240101U UMETA(DisplayName = "Utm Latitude"),
	UtmLongitude = 240102U UMETA(DisplayName = "Utm Longitude"),
	VhfFrequency = 240103U UMETA(DisplayName = "Vhf Frequency"),
	VisibilityRange = 240104U UMETA(DisplayName = "Visibility Range"),
	VoidAaaHit = 240105U UMETA(DisplayName = "Void Aaa Hit"),
	VoidCollision = 240106U UMETA(DisplayName = "Void Collision"),
	VoidEarthHit = 240107U UMETA(DisplayName = "Void Earth Hit"),
	VoidFriendly = 240108U UMETA(DisplayName = "Void Friendly"),
	VoidGunHit = 240109U UMETA(DisplayName = "Void Gun Hit"),
	VoidRocketHit = 240110U UMETA(DisplayName = "Void Rocket Hit"),
	VoidSamHit = 240111U UMETA(DisplayName = "Void Sam Hit"),
	WeaponData = 240112U UMETA(DisplayName = "Weapon Data"),
	WeaponType = 240113U UMETA(DisplayName = "Weapon Type"),
	Weather_New = 240114U UMETA(DisplayName = "Weather (New)"),
	WindDirection_New = 240115U UMETA(DisplayName = "Wind Direction (New)"),
	WindSpeed = 240116U UMETA(DisplayName = "Wind Speed"),
	WingStation = 240117U UMETA(DisplayName = "Wing Station"),
	Yaw = 240118U UMETA(DisplayName = "Yaw"),
	MemoryOffset = 240119U UMETA(DisplayName = "Memory Offset"),
	MemoryData = 240120U UMETA(DisplayName = "Memory Data"),
	VASI = 240121U UMETA(DisplayName = "VASI"),
	Beacon = 240122U UMETA(DisplayName = "Beacon"),
	Strobe = 240123U UMETA(DisplayName = "Strobe"),
	Culture = 240124U UMETA(DisplayName = "Culture"),
	Approach = 240125U UMETA(DisplayName = "Approach"),
	RunwayEnd = 240126U UMETA(DisplayName = "Runway End"),
	Obstruction = 240127U UMETA(DisplayName = "Obstruction"),
	RunwayEdge = 240128U UMETA(DisplayName = "Runway Edge"),
	RampTaxiway = 240129U UMETA(DisplayName = "Ramp Taxiway"),
	LaserBombCode = 240130U UMETA(DisplayName = "Laser Bomb Code"),
	RackType = 240131U UMETA(DisplayName = "Rack Type"),
	HUD = 240132U UMETA(DisplayName = "HUD"),
	RoleFileName = 240133U UMETA(DisplayName = "RoleFileName"),
	PilotName = 240134U UMETA(DisplayName = "PilotName"),
	PilotDesignation = 240135U UMETA(DisplayName = "PilotDesignation"),
	ModelType = 240136U UMETA(DisplayName = "Model Type"),
	DISType = 240137U UMETA(DisplayName = "DIS Type"),
	Class = 240138U UMETA(DisplayName = "Class"),
	Channel = 240139U UMETA(DisplayName = "Channel"),
	EntityType_New = 240140U UMETA(DisplayName = "Entity Type (New)"),
	AlternativeEntityType_New = 240141U UMETA(DisplayName = "Alternative Entity Type (New)"),
	EntityLocation = 240142U UMETA(DisplayName = "Entity Location"),
	EntityLinearVelocity = 240143U UMETA(DisplayName = "Entity Linear Velocity"),
	EntityOrientation = 240144U UMETA(DisplayName = "Entity Orientation"),
	DeadReckoning = 240145U UMETA(DisplayName = "Dead Reckoning"),
	FailureSymptom = 240146U UMETA(DisplayName = "Failure Symptom"),
	MaxFuel = 240147U UMETA(DisplayName = "Max Fuel"),
	RefuelingBoomConnect = 240148U UMETA(DisplayName = "Refueling Boom Connect"),
	AltitudeAGL = 240149U UMETA(DisplayName = "Altitude AGL"),
	CalibratedAirspeed = 240150U UMETA(DisplayName = "Calibrated Airspeed"),
	TACANChannel = 240151U UMETA(DisplayName = "TACAN Channel"),
	TACANBand = 240152U UMETA(DisplayName = "TACAN Band"),
	TACANMode = 240153U UMETA(DisplayName = "TACAN Mode"),
	Munition = 500001U UMETA(DisplayName = "Munition"),
	EngineFuel = 500002U UMETA(DisplayName = "Engine Fuel"),
	StorageFuel = 500003U UMETA(DisplayName = "Storage Fuel"),
	NotUsed = 500004U UMETA(DisplayName = "Not Used"),
	Expendable = 500005U UMETA(DisplayName = "Expendable"),
	TotalRecordSets = 500006U UMETA(DisplayName = "Total Record Sets"),
	LaunchedMunition = 500007U UMETA(DisplayName = "Launched Munition"),
	Association = 500008U UMETA(DisplayName = "Association"),
	Sensor = 500009U UMETA(DisplayName = "Sensor"),
	MunitionReload = 500010U UMETA(DisplayName = "Munition Reload"),
	EngineFuelReload = 500011U UMETA(DisplayName = "Engine Fuel Reload"),
	StorageFuelReload = 500012U UMETA(DisplayName = "Storage Fuel Reload"),
	ExpendableReload = 500013U UMETA(DisplayName = "Expendable Reload")
};