// Copyright 2022 Gaming Research Integration for Learning Lab. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"

//Blueprints don't currently support non-uint8 enums.
enum class EVariableRecordTypes : uint32
{
	Other_Zero,
	HighFidelityHAVEQUICKRadio UMETA(DisplayName = "High Fidelity HAVE QUICK Radio") = 3000U,
	BlankingSectorattributerecord UMETA(DisplayName = "Blanking Sector attribute record") = 3500U,
	AngleDeceptionattributerecord UMETA(DisplayName = "Angle Deception attribute record") = 3501U,
	FalseTargetsattributerecord UMETA(DisplayName = "False Targets attribute record") = 3502U,
	DEPrecisionAimpointrecord UMETA(DisplayName = "DE Precision Aimpoint record") = 4000U,
	DEAreaAimpointrecord UMETA(DisplayName = "DE Area Aimpoint record") = 4001U,
	DirectedEnergyDamageDescriptionrecord UMETA(DisplayName = "Directed Energy Damage Description record") = 4500U,
	CryptoControl UMETA(DisplayName = "Crypto Control") = 5000U,
	Mode5_STransponderLocation UMETA(DisplayName = "Mode 5/S Transponder Location") = 5001U,
	Mode5_STransponderLocationError UMETA(DisplayName = "Mode 5/S Transponder Location Error") = 5002U,
	SquitterAirbornePositionReport UMETA(DisplayName = "Squitter Airborne Position Report") = 5003U,
	SquitterAirborneVelocityReport UMETA(DisplayName = "Squitter Airborne Velocity Report") = 5004U,
	SquitterSurfacePositionReport UMETA(DisplayName = "Squitter Surface Position Report") = 5005U,
	SquitterIdentificationReport UMETA(DisplayName = "Squitter Identification Report") = 5006U,
	GICB UMETA(DisplayName = "GICB") = 5007U,
	SquitterEventDrivenReport UMETA(DisplayName = "Squitter Event-Driven Report") = 5008U,
	AntennaLocation UMETA(DisplayName = "Antenna Location") = 5009U,
	BasicInteractive UMETA(DisplayName = "Basic Interactive") = 5010U,
	InteractiveMode4Reply UMETA(DisplayName = "Interactive Mode 4 Reply") = 5011U,
	InteractiveMode5Reply UMETA(DisplayName = "Interactive Mode 5 Reply") = 5012U,
	InteractiveBasicMode5 UMETA(DisplayName = "Interactive Basic Mode 5") = 5013U,
	InteractiveBasicModeS UMETA(DisplayName = "Interactive Basic Mode S") = 5014U,
	IOEffect UMETA(DisplayName = "IO Effect") = 5500U,
	IOCommunicationsNode UMETA(DisplayName = "IO Communications Node") = 5501U,
	Identification UMETA(DisplayName = "Identification") = 10000U,
	EntityType UMETA(DisplayName = "Entity Type") = 11000U,
	Concatenated UMETA(DisplayName = "Concatenated") = 11100U,
	Kind_New UMETA(DisplayName = "Kind (New)") = 11110U,
	Domain_New UMETA(DisplayName = "Domain (New)") = 11120U,
	Country_New UMETA(DisplayName = "Country (New)") = 11130U,
	Category_New UMETA(DisplayName = "Category (New)") = 11140U,
	Subcategory_New UMETA(DisplayName = "Subcategory (New)") = 11150U,
	Specific_New UMETA(DisplayName = "Specific (New)") = 11160U,
	Extra_New UMETA(DisplayName = "Extra (New)") = 11170U,
	ForceID UMETA(DisplayName = "Force ID") = 11200U,
	Description_New UMETA(DisplayName = "Description (New)") = 11300U,
	AlternativeEntityType UMETA(DisplayName = "Alternative Entity Type") = 12000U,
	Kind_AlsoNew UMETA(DisplayName = "Kind (Also New)") = 12110U,
	Domain_AlsoNew UMETA(DisplayName = "Domain (Also New)") = 12120U,
	Country_AlsoNew UMETA(DisplayName = "Country (Also New)") = 12130U,
	Category_AlsoNew UMETA(DisplayName = "Category (Also New)") = 12140U,
	Subcategory_AlsoNew UMETA(DisplayName = "Subcategory (Also New)") = 12150U,
	Specific_AlsoNew UMETA(DisplayName = "Specific (Also New)") = 12160U,
	Extra_AlsoNew UMETA(DisplayName = "Extra (Also New)") = 12170U,
	Description_AlsoNew UMETA(DisplayName = "Description (Also New)") = 12300U,
	EntityMarking UMETA(DisplayName = "Entity Marking") = 13000U,
	EntityMarkingCharacters UMETA(DisplayName = "Entity Marking Characters") = 13100U,
	CrewID UMETA(DisplayName = "Crew ID") = 13200U,
	TaskOrganization UMETA(DisplayName = "Task Organization") = 14000U,
	RegimentName UMETA(DisplayName = "Regiment Name") = 14200U,
	BattalionName UMETA(DisplayName = "Battalion Name") = 14300U,
	CompanyName UMETA(DisplayName = "Company Name") = 14400U,
	PlatoonName UMETA(DisplayName = "Platoon Name") = 14500U,
	SquadName UMETA(DisplayName = "Squad Name") = 14520U,
	TeamName UMETA(DisplayName = "Team Name") = 14540U,
	BumperNumber UMETA(DisplayName = "Bumper Number") = 14600U,
	VehicleNumber UMETA(DisplayName = "Vehicle Number") = 14700U,
	UnitNumber UMETA(DisplayName = "Unit Number") = 14800U,
	DISIdentity UMETA(DisplayName = "DIS Identity") = 15000U,
	DISSiteID UMETA(DisplayName = "DIS Site ID") = 15100U,
	DISHostID UMETA(DisplayName = "DIS Host ID") = 15200U,
	DISEntityID UMETA(DisplayName = "DIS Entity ID") = 15300U,
	MountIntent UMETA(DisplayName = "Mount Intent") = 15400U,
	TetherUnthetherCommandID UMETA(DisplayName = "Tether-Unthether Command ID") = 15500U,
	TeleportEntityDataRecord UMETA(DisplayName = "Teleport Entity Data Record") = 15510U,
	DISAggregateIDSetifcommunicationtoaggregate UMETA(DisplayName = "DIS Aggregate ID (Set if communication to aggregate)") = 15600U,
	OwnershipStatus UMETA(DisplayName = "Ownership Status") = 15800U,
	Loads UMETA(DisplayName = "Loads") = 20000U,
	CrewMembers UMETA(DisplayName = "Crew Members") = 21000U,
	CrewMemberID UMETA(DisplayName = "Crew Member ID") = 21100U,
	Health UMETA(DisplayName = "Health") = 21200U,
	JobAssignment UMETA(DisplayName = "Job Assignment") = 21300U,
	Fuel UMETA(DisplayName = "Fuel") = 23000U,
	Quantity UMETA(DisplayName = "Quantity") = 23100U,
	Quantity_New UMETA(DisplayName = "Quantity (New)") = 23105U,
	Ammunition UMETA(DisplayName = "Ammunition") = 24000U,
	OneHundredTwentymmHEAT_quantity UMETA(DisplayName = "120-mm HEAT, quantity") = 24001U,
	OneHundredTwentymmSABOT_quantity UMETA(DisplayName = "120-mm SABOT, quantity") = 24002U,
	Twelve_7mmM8_quantity UMETA(DisplayName = "12.7-mm M8, quantity") = 24003U,
	Twelve_7mmM20_quantity UMETA(DisplayName = "12.7-mm M20, quantity") = 24004U,
	Seven_62mmM62_quantity UMETA(DisplayName = "7.62-mm M62, quantity") = 24005U,
	M250UKL8A1_quantity UMETA(DisplayName = "M250 UKL8A1, quantity") = 24006U,
	M250UKL8A3_quantity UMETA(DisplayName = "M250 UKL8A3, quantity") = 24007U,
	Seven_62mmM80_quantity UMETA(DisplayName = "7.62-mm M80, quantity") = 24008U,
	Twelve_7mm_quantity UMETA(DisplayName = "12.7-mm, quantity") = 24009U,
	Seven_62mm_quantity UMETA(DisplayName = "7.62-mm, quantity") = 24010U,
	Mines_quantity UMETA(DisplayName = "Mines, quantity") = 24060U,
	Type UMETA(DisplayName = "Type") = 24100U,
	Kind UMETA(DisplayName = "Kind") = 24110U,
	Domain UMETA(DisplayName = "Domain") = 24120U,
	Country UMETA(DisplayName = "Country") = 24130U,
	Category UMETA(DisplayName = "Category") = 24140U,
	Subcategory UMETA(DisplayName = "Subcategory") = 24150U,
	Extra UMETA(DisplayName = "Extra") = 24160U,
	Description UMETA(DisplayName = "Description") = 24300U,
	Cargo UMETA(DisplayName = "Cargo") = 25000U,
	VehicleMass UMETA(DisplayName = "Vehicle Mass") = 26000U,
	SupplyQuantity UMETA(DisplayName = "Supply Quantity") = 27000U,
	Armament UMETA(DisplayName = "Armament") = 28000U,
	Status UMETA(DisplayName = "Status") = 30000U,
	Activateentity UMETA(DisplayName = "Activate entity") = 30010U,
	SubscriptionState UMETA(DisplayName = "Subscription State") = 30100U,
	Roundtriptimedelay UMETA(DisplayName = "Round trip time delay") = 30300U,
	TADILJmessagecountlabel0 UMETA(DisplayName = "TADIL J message count (label 0)") = 30400U,
	TADILJmessagecountlabel1 UMETA(DisplayName = "TADIL J message count (label 1)") = 30401U,
	TADILJmessagecountlabel2 UMETA(DisplayName = "TADIL J message count (label 2)") = 30402U,
	TADILJmessagecountlabel3 UMETA(DisplayName = "TADIL J message count (label 3)") = 30403U,
	TADILJmessagecountlabel4 UMETA(DisplayName = "TADIL J message count (label 4)") = 30404U,
	TADILJmessagecountlabel5 UMETA(DisplayName = "TADIL J message count (label 5)") = 30405U,
	TADILJmessagecountlabel6 UMETA(DisplayName = "TADIL J message count (label 6)") = 30406U,
	TADILJmessagecountlabel7 UMETA(DisplayName = "TADIL J message count (label 7)") = 30407U,
	TADILJmessagecountlabel8 UMETA(DisplayName = "TADIL J message count (label 8)") = 30408U,
	TADILJmessagecountlabel9 UMETA(DisplayName = "TADIL J message count (label 9)") = 30409U,
	TADILJmessagecountlabel10 UMETA(DisplayName = "TADIL J message count (label 10)") = 30410U,
	TADILJmessagecountlabel11 UMETA(DisplayName = "TADIL J message count (label 11)") = 30411U,
	TADILJmessagecountlabel12 UMETA(DisplayName = "TADIL J message count (label 12)") = 30412U,
	TADILJmessagecountlabel13 UMETA(DisplayName = "TADIL J message count (label 13)") = 30413U,
	TADILJmessagecountlabel14 UMETA(DisplayName = "TADIL J message count (label 14)") = 30414U,
	TADILJmessagecountlabel15 UMETA(DisplayName = "TADIL J message count (label 15)") = 30415U,
	TADILJmessagecountlabel16 UMETA(DisplayName = "TADIL J message count (label 16)") = 30416U,
	TADILJmessagecountlabel17 UMETA(DisplayName = "TADIL J message count (label 17)") = 30417U,
	TADILJmessagecountlabel18 UMETA(DisplayName = "TADIL J message count (label 18)") = 30418U,
	TADILJmessagecountlabel19 UMETA(DisplayName = "TADIL J message count (label 19)") = 30419U,
	TADILJmessagecountlabel20 UMETA(DisplayName = "TADIL J message count (label 20)") = 30420U,
	TADILJmessagecountlabel21 UMETA(DisplayName = "TADIL J message count (label 21)") = 30421U,
	TADILJmessagecountlabel22 UMETA(DisplayName = "TADIL J message count (label 22)") = 30422U,
	TADILJmessagecountlabel23 UMETA(DisplayName = "TADIL J message count (label 23)") = 30423U,
	TADILJmessagecountlabel24 UMETA(DisplayName = "TADIL J message count (label 24)") = 30424U,
	TADILJmessagecountlabel25 UMETA(DisplayName = "TADIL J message count (label 25)") = 30425U,
	TADILJmessagecountlabel26 UMETA(DisplayName = "TADIL J message count (label 26)") = 30426U,
	TADILJmessagecountlabel27 UMETA(DisplayName = "TADIL J message count (label 27)") = 30427U,
	TADILJmessagecountlabel28 UMETA(DisplayName = "TADIL J message count (label 28)") = 30428U,
	TADILJmessagecountlabel29 UMETA(DisplayName = "TADIL J message count (label 29)") = 30429U,
	TADILJmessagecountlabel30 UMETA(DisplayName = "TADIL J message count (label 30)") = 30430U,
	TADILJmessagecountlabel31 UMETA(DisplayName = "TADIL J message count (label 31)") = 30431U,
	Position UMETA(DisplayName = "Position") = 31000U,
	RouteWaypointtype UMETA(DisplayName = "Route (Waypoint) type") = 31010U,
	MilGrid10 UMETA(DisplayName = "MilGrid10") = 31100U,
	GeocentricCoordinates UMETA(DisplayName = "Geocentric Coordinates") = 31200U,
	X_New UMETA(DisplayName = "X (New)") = 31210U,
	Y_New UMETA(DisplayName = "Y (New)") = 31220U,
	Z_New UMETA(DisplayName = "Z (New)") = 31230U,
	Latitude UMETA(DisplayName = "Latitude") = 31300U,
	Longitude UMETA(DisplayName = "Longitude") = 31400U,
	LineofSight UMETA(DisplayName = "Line of Sight") = 31500U,
	X_AlsoNew UMETA(DisplayName = "X (Also New)") = 31510U,
	Y_AlsoNew UMETA(DisplayName = "Y (Also New)") = 31520U,
	Z_AlsoNew UMETA(DisplayName = "Z (Also New)") = 31530U,
	Altitude UMETA(DisplayName = "Altitude") = 31600U,
	DestinationLatitude UMETA(DisplayName = "Destination Latitude") = 31700U,
	DestinationLongitude UMETA(DisplayName = "Destination Longitude") = 31800U,
	DestinationAltitude UMETA(DisplayName = "Destination Altitude") = 31900U,
	Orientation UMETA(DisplayName = "Orientation") = 32000U,
	HullHeadingAngle UMETA(DisplayName = "Hull Heading Angle") = 32100U,
	HullPitchAngle UMETA(DisplayName = "Hull Pitch Angle") = 32200U,
	RollAngle UMETA(DisplayName = "Roll Angle") = 32300U,
	X_FinalNew UMETA(DisplayName = "X (Final New)") = 32500U,
	Y_FinalNew UMETA(DisplayName = "Y (Final New)") = 32600U,
	Z_FinalNew UMETA(DisplayName = "Z (Final New)") = 32700U,
	Appearance UMETA(DisplayName = "Appearance") = 33000U,
	AmbientLighting UMETA(DisplayName = "Ambient Lighting") = 33100U,
	Lights UMETA(DisplayName = "Lights") = 33101U,
	PaintScheme UMETA(DisplayName = "Paint Scheme") = 33200U,
	Smoke UMETA(DisplayName = "Smoke") = 33300U,
	TrailingEffects UMETA(DisplayName = "Trailing Effects") = 33400U,
	Flaming UMETA(DisplayName = "Flaming") = 33500U,
	Marking UMETA(DisplayName = "Marking") = 33600U,
	MinePlowsAttached UMETA(DisplayName = "Mine Plows Attached") = 33710U,
	MineRollersAttached UMETA(DisplayName = "Mine Rollers Attached") = 33720U,
	TankTurretAzimuth UMETA(DisplayName = "Tank Turret Azimuth") = 33730U,
	FailuresandMalfunctions UMETA(DisplayName = "Failures and Malfunctions") = 34000U,
	Age UMETA(DisplayName = "Age") = 34100U,
	Kilometers UMETA(DisplayName = "Kilometers") = 34110U,
	Damage UMETA(DisplayName = "Damage") = 35000U,
	Cause UMETA(DisplayName = "Cause") = 35050U,
	MobilityKill UMETA(DisplayName = "Mobility Kill") = 35100U,
	FirePowerKill UMETA(DisplayName = "Fire-Power Kill") = 35200U,
	PersonnelCasualties UMETA(DisplayName = "Personnel Casualties") = 35300U,
	Velocity UMETA(DisplayName = "Velocity") = 36000U,
	Xvelocity UMETA(DisplayName = "X-velocity") = 36100U,
	Yvelocity UMETA(DisplayName = "Y-velocity") = 36200U,
	Zvelocity UMETA(DisplayName = "Z-velocity") = 36300U,
	Speed_New UMETA(DisplayName = "Speed (New)") = 36400U,
	Acceleration UMETA(DisplayName = "Acceleration") = 37000U,
	Xacceleration UMETA(DisplayName = "X-acceleration") = 37100U,
	Yacceleration UMETA(DisplayName = "Y-acceleration") = 37200U,
	Zacceleration UMETA(DisplayName = "Z-acceleration") = 37300U,
	EngineStatus UMETA(DisplayName = "Engine Status") = 38100U,
	PrimaryTargetLinePTL UMETA(DisplayName = "Primary Target Line (PTL)") = 39000U,
	Exercise UMETA(DisplayName = "Exercise") = 40000U,
	ExerciseState UMETA(DisplayName = "Exercise State") = 40010U,
	Restart_Refresh UMETA(DisplayName = "Restart/Refresh") = 40015U,
	AFATDSFileName UMETA(DisplayName = "AFATDS File Name") = 40020U,
	TerrainDatabase UMETA(DisplayName = "Terrain Database") = 41000U,
	Missions UMETA(DisplayName = "Missions") = 42000U,
	MissionID UMETA(DisplayName = "Mission ID") = 42100U,
	MissionType UMETA(DisplayName = "Mission Type") = 42200U,
	MissionRequestTimeStamp UMETA(DisplayName = "Mission Request Time Stamp") = 42300U,
	ExerciseDescription UMETA(DisplayName = "Exercise Description") = 43000U,
	Name UMETA(DisplayName = "Name") = 43100U,
	Entities UMETA(DisplayName = "Entities") = 43200U,
	Version UMETA(DisplayName = "Version") = 43300U,
	GuiseMode UMETA(DisplayName = "Guise Mode") = 43410U,
	SimulationApplicationActiveStatus UMETA(DisplayName = "Simulation Application Active Status") = 43420U,
	SimulationApplicationRoleRecord UMETA(DisplayName = "Simulation Application Role Record") = 43430U,
	SimulationApplicationState UMETA(DisplayName = "Simulation Application State") = 43440U,
	VisualOutputMode UMETA(DisplayName = "Visual Output Mode") = 44000U,
	SimulationManagerRole UMETA(DisplayName = "Simulation Manager Role") = 44100U,
	SimulationManagerSiteID UMETA(DisplayName = "Simulation Manager Site ID") = 44110U,
	SimulationManagerApplic_ID UMETA(DisplayName = "Simulation Manager Applic. ID") = 44120U,
	SimulationManagerEntityID UMETA(DisplayName = "Simulation Manager Entity ID") = 44130U,
	SimulationManagerActiveStatus UMETA(DisplayName = "Simulation Manager Active Status") = 44140U,
	AfterActiveReviewRole UMETA(DisplayName = "After Active Review Role") = 44200U,
	AfterActiveReviewSiteID UMETA(DisplayName = "After Active Review Site ID") = 44210U,
	AfterActiveApplic_ID UMETA(DisplayName = "After Active Applic. ID") = 44220U,
	AfterActiveReviewEntityID UMETA(DisplayName = "After Active Review Entity ID") = 44230U,
	AfterActiveReviewActiveStatus UMETA(DisplayName = "After Active Review Active Status") = 44240U,
	ExerciseLoggerRole UMETA(DisplayName = "Exercise Logger Role") = 44300U,
	ExerciseLoggerSiteID UMETA(DisplayName = "Exercise Logger Site ID") = 44310U,
	ExerciseLoggerApplic_ID UMETA(DisplayName = "Exercise Logger Applic. ID") = 44320U,
	ExerciseEntityID UMETA(DisplayName = "Exercise Entity ID") = 44330U,
	ExerciseLoggerActiveStatus UMETA(DisplayName = "Exercise Logger Active Status") = 44340U,
	SyntheticEnvironmentManagerRole UMETA(DisplayName = "Synthetic Environment Manager Role") = 44400U,
	SyntheticEnvironmentManagerSiteID UMETA(DisplayName = "Synthetic Environment Manager Site ID") = 44410U,
	SyntheticEnvironmentManagerApplic_ID UMETA(DisplayName = "Synthetic Environment Manager Applic. ID") = 44420U,
	SyntheticEnvironmentManagerEntityID UMETA(DisplayName = "Synthetic Environment Manager Entity ID") = 44430U,
	SyntheticEnvironmentManagerActiveStatus UMETA(DisplayName = "Synthetic Environment Manager Active Status") = 44440U,
	SIMNETDISTranslatorRole UMETA(DisplayName = "SIMNET-DIS Translator Role") = 44500U,
	SIMNETDISTranslatorSiteID UMETA(DisplayName = "SIMNET-DIS Translator Site ID") = 44510U,
	SIMNETDISTranslatorApplic_ID UMETA(DisplayName = "SIMNET-DIS Translator Applic. ID") = 44520U,
	SIMNETDISTranslatorEntityID UMETA(DisplayName = "SIMNET-DIS Translator Entity ID") = 44530U,
	SIMNETDISTranslatorActiveStatus UMETA(DisplayName = "SIMNET-DIS Translator Active Status") = 44540U,
	ApplicationRate UMETA(DisplayName = "Application Rate") = 45000U,
	ApplicationTime UMETA(DisplayName = "Application Time") = 45005U,
	ApplicationTimestep UMETA(DisplayName = "Application Timestep") = 45010U,
	FeedbackTime UMETA(DisplayName = "Feedback Time") = 45020U,
	SimulationRate UMETA(DisplayName = "Simulation Rate") = 45030U,
	SimulationTime UMETA(DisplayName = "Simulation Time") = 45040U,
	SimulationTimestep UMETA(DisplayName = "Simulation Timestep") = 45050U,
	TimeInterval UMETA(DisplayName = "Time Interval") = 45060U,
	TimeLatency UMETA(DisplayName = "Time Latency") = 45070U,
	TimeScheme UMETA(DisplayName = "Time Scheme") = 45080U,
	ExerciseElapsedTime UMETA(DisplayName = "Exercise Elapsed Time") = 46000U,
	ElapsedTime UMETA(DisplayName = "Elapsed Time") = 46010U,
	Environment UMETA(DisplayName = "Environment") = 50000U,
	Weather UMETA(DisplayName = "Weather") = 51000U,
	WeatherCondition UMETA(DisplayName = "Weather Condition") = 51010U,
	ThermalCondition UMETA(DisplayName = "Thermal Condition") = 51100U,
	ThermalVisibility UMETA(DisplayName = "Thermal Visibility") = 51110U,
	ThermalVisibility_New UMETA(DisplayName = "Thermal Visibility (New)") = 51111U,
	Time UMETA(DisplayName = "Time") = 52000U,
	Time_New UMETA(DisplayName = "Time (New)") = 52001U,
	TimeofDay_Discrete UMETA(DisplayName = "Time of Day, Discrete") = 52100U,
	TimeofDay_Continuous UMETA(DisplayName = "Time of Day, Continuous") = 52200U,
	TimeMode UMETA(DisplayName = "Time Mode") = 52300U,
	TimeScene UMETA(DisplayName = "Time Scene") = 52305U,
	CurrentHour UMETA(DisplayName = "Current Hour") = 52310U,
	CurrentMinute UMETA(DisplayName = "Current Minute") = 52320U,
	CurrentSecond UMETA(DisplayName = "Current Second") = 52330U,
	Azimuth_New UMETA(DisplayName = "Azimuth (New)") = 52340U,
	MaximumElevation UMETA(DisplayName = "Maximum Elevation") = 52350U,
	TimeZone UMETA(DisplayName = "Time Zone") = 52360U,
	TimeRate UMETA(DisplayName = "Time Rate") = 52370U,
	SimSecondsSinceExerciseStart UMETA(DisplayName = "The number of simulation seconds since the start of the exercise (simulation time)") = 52380U,
	TimeSunriseEnabled UMETA(DisplayName = "Time Sunrise Enabled") = 52400U,
	SunriseHour UMETA(DisplayName = "Sunrise Hour") = 52410U,
	SunriseMinute UMETA(DisplayName = "Sunrise Minute") = 52420U,
	SunriseSecond UMETA(DisplayName = "Sunrise Second") = 52430U,
	SunriseAzimuth UMETA(DisplayName = "Sunrise Azimuth") = 52440U,
	TimeSunsetEnabled UMETA(DisplayName = "Time Sunset Enabled") = 52500U,
	SunsetHour UMETA(DisplayName = "Sunset Hour") = 52510U,
	SunsetHour_New UMETA(DisplayName = "Sunset Hour (New)") = 52511U,
	SunsetMinute UMETA(DisplayName = "Sunset Minute") = 52520U,
	SunsetSecond UMETA(DisplayName = "Sunset Second") = 52530U,
	Date UMETA(DisplayName = "Date") = 52600U,
	DateEuropean UMETA(DisplayName = "Date (European)") = 52601U,
	DateUS UMETA(DisplayName = "Date (US)") = 52602U,
	Month UMETA(DisplayName = "Month") = 52610U,
	Day UMETA(DisplayName = "Day") = 52620U,
	Year UMETA(DisplayName = "Year") = 52630U,
	Clouds UMETA(DisplayName = "Clouds") = 53000U,
	CloudLayerEnable UMETA(DisplayName = "Cloud Layer Enable") = 53050U,
	CloudLayerSelection UMETA(DisplayName = "Cloud Layer Selection") = 53060U,
	Visibility UMETA(DisplayName = "Visibility") = 53100U,
	BaseAltitude UMETA(DisplayName = "Base Altitude") = 53200U,
	BaseAltitude_New UMETA(DisplayName = "Base Altitude (New)") = 53250U,
	Ceiling UMETA(DisplayName = "Ceiling") = 53300U,
	Ceiling_New UMETA(DisplayName = "Ceiling (New)") = 53350U,
	Characteristics UMETA(DisplayName = "Characteristics") = 53400U,
	ConcentrationLength UMETA(DisplayName = "Concentration Length") = 53410U,
	Transmittance UMETA(DisplayName = "Transmittance") = 53420U,
	Radiance UMETA(DisplayName = "Radiance") = 53430U,
	Precipitation UMETA(DisplayName = "Precipitation") = 54000U,
	Rain UMETA(DisplayName = "Rain") = 54100U,
	Fog UMETA(DisplayName = "Fog") = 55000U,
	Visibility_New UMETA(DisplayName = "Visibility (New)") = 55100U,
	Visibility_AlsoNew UMETA(DisplayName = "Visibility (Also New)") = 55101U,
	Visibility_NewAsWell UMETA(DisplayName = "Visibility (New As Well)") = 55105U,
	Density UMETA(DisplayName = "Density") = 55200U,
	Base UMETA(DisplayName = "Base") = 55300U,
	ViewLayerfromabove_ UMETA(DisplayName = "View Layer from above.") = 55401U,
	TransitionRange UMETA(DisplayName = "Transition Range") = 55410U,
	Bottom UMETA(DisplayName = "Bottom") = 55420U,
	Bottom_New UMETA(DisplayName = "Bottom (New)") = 55425U,
	Ceiling_AlsoNew UMETA(DisplayName = "Ceiling (Also New)") = 55430U,
	Ceiling_NewAsWell UMETA(DisplayName = "Ceiling (New As Well)") = 55435U,
	HeavenlyBodies UMETA(DisplayName = "Heavenly Bodies") = 56000U,
	Sun UMETA(DisplayName = "Sun") = 56100U,
	SunVisible UMETA(DisplayName = "Sun Visible") = 56105U,
	Position_New UMETA(DisplayName = "Position (New)") = 56110U,
	SunPositionElevation_Degrees UMETA(DisplayName = "Sun Position Elevation, Degrees") = 56111U,
	PositionAzimuth UMETA(DisplayName = "Position Azimuth") = 56120U,
	SunPositionAzimuth_Degrees UMETA(DisplayName = "Sun Position Azimuth, Degrees") = 56121U,
	PositionElevation UMETA(DisplayName = "Position Elevation") = 56130U,
	PositionIntensity UMETA(DisplayName = "Position Intensity") = 56140U,
	Moon UMETA(DisplayName = "Moon") = 56200U,
	MoonVisible UMETA(DisplayName = "Moon Visible") = 56205U,
	Position_AlsoNew UMETA(DisplayName = "Position (Also New)") = 56210U,
	PositionAzimuth_New UMETA(DisplayName = "Position Azimuth (New)") = 56220U,
	MoonPositionAzimuth_Degrees UMETA(DisplayName = "Moon Position Azimuth, Degrees") = 56221U,
	PositionElevation_New UMETA(DisplayName = "Position Elevation (New)") = 56230U,
	MoonPositionElevation_Degrees UMETA(DisplayName = "Moon Position Elevation, Degrees") = 56231U,
	PositionIntensity_New UMETA(DisplayName = "Position Intensity (New)") = 56240U,
	Horizon UMETA(DisplayName = "Horizon") = 56310U,
	HorizonAzimuth UMETA(DisplayName = "Horizon Azimuth") = 56320U,
	HorizonElevation UMETA(DisplayName = "Horizon Elevation") = 56330U,
	HorizonHeading UMETA(DisplayName = "Horizon Heading") = 56340U,
	HorizonIntensity UMETA(DisplayName = "Horizon Intensity") = 56350U,
	Humidity UMETA(DisplayName = "Humidity") = 57200U,
	Visibility_YetAnother UMETA(DisplayName = "Visibility (Yet Another)") = 57300U,
	Winds UMETA(DisplayName = "Winds") = 57400U,
	Speed UMETA(DisplayName = "Speed") = 57410U,
	WindSpeed_Knots UMETA(DisplayName = "Wind Speed, Knots") = 57411U,
	WindDirection UMETA(DisplayName = "Wind Direction") = 57420U,
	WindDirection_Degrees UMETA(DisplayName = "Wind Direction, Degrees") = 57421U,
	Rainsoak UMETA(DisplayName = "Rainsoak") = 57500U,
	TideSpeed UMETA(DisplayName = "Tide Speed") = 57610U,
	TideSpeed_Knots UMETA(DisplayName = "Tide Speed, Knots") = 57611U,
	TideDirection UMETA(DisplayName = "Tide Direction") = 57620U,
	TideDirection_Degrees UMETA(DisplayName = "Tide Direction, Degrees") = 57621U,
	Haze UMETA(DisplayName = "Haze") = 58000U,
	Visibility_AnotherNew UMETA(DisplayName = "Visibility (Another New)") = 58100U,
	Visibility_FinalNew UMETA(DisplayName = "Visibility (Final New)") = 58105U,
	Density_New UMETA(DisplayName = "Density_New") = 58200U,
	Ceiling_AnotherNew UMETA(DisplayName = "Ceiling (Another New)") = 58430U,
	Ceiling_FinalNew UMETA(DisplayName = "Ceiling (Final New)") = 58435U,
	ContaminantsandObscurants UMETA(DisplayName = "Contaminants and Obscurants") = 59000U,
	Contaminant_ObscurantType UMETA(DisplayName = "Contaminant/Obscurant Type") = 59100U,
	Persistence UMETA(DisplayName = "Persistence") = 59110U,
	ChemicalDosage UMETA(DisplayName = "Chemical Dosage") = 59115U,
	ChemicalAirConcentration UMETA(DisplayName = "Chemical Air Concentration") = 59120U,
	ChemicalGroundDeposition UMETA(DisplayName = "Chemical Ground Deposition") = 59125U,
	ChemicalMaximumGroundDeposition UMETA(DisplayName = "Chemical Maximum Ground Deposition") = 59130U,
	ChemicalDosageThreshold UMETA(DisplayName = "Chemical Dosage Threshold") = 59135U,
	BiologicalDosage UMETA(DisplayName = "Biological Dosage") = 59140U,
	BiologicalAirConcentration UMETA(DisplayName = "Biological Air Concentration") = 59145U,
	BiologicalDosageThreshold UMETA(DisplayName = "Biological Dosage Threshold") = 59150U,
	BiologicalBinnedParticleCount UMETA(DisplayName = "Biological Binned Particle Count") = 59155U,
	RadiologicalDosage UMETA(DisplayName = "Radiological Dosage") = 59160U,
	Communications UMETA(DisplayName = "Communications") = 60000U,
	ChannelType UMETA(DisplayName = "Channel Type") = 61100U,
	ChannelType_New UMETA(DisplayName = "Channel Type (New)") = 61101U,
	ChannelIdentification UMETA(DisplayName = "Channel Identification") = 61200U,
	AlphaIdentification UMETA(DisplayName = "Alpha Identification") = 61300U,
	RadioIdentification UMETA(DisplayName = "Radio Identification") = 61400U,
	LandLineIdentification UMETA(DisplayName = "Land Line Identification") = 61500U,
	IntercomIdentification UMETA(DisplayName = "Intercom Identification") = 61600U,
	GroupNetworkChannelNumber UMETA(DisplayName = "Group Network Channel Number") = 61700U,
	RadioCommunicationsStatus UMETA(DisplayName = "Radio Communications Status") = 62100U,
	StationaryRadioTransmittersDefaultTime UMETA(DisplayName = "Stationary Radio Transmitters Default Time") = 62200U,
	MovingRadioTransmittersDefaultTime UMETA(DisplayName = "Moving Radio Transmitters Default Time") = 62300U,
	StationaryRadioSignalsDefaultTime UMETA(DisplayName = "Stationary Radio Signals Default Time") = 62400U,
	MovingRadioSignalDefaultTime UMETA(DisplayName = "Moving Radio Signal Default Time") = 62500U,
	RadioInitializationTransecSecurityKey UMETA(DisplayName = "Radio Initialization Transec Security Key") = 63101U,
	RadioInitializationInternalNoiseLevel UMETA(DisplayName = "Radio Initialization Internal Noise Level") = 63102U,
	RadioInitializationSquelchThreshold UMETA(DisplayName = "Radio Initialization Squelch Threshold") = 63103U,
	RadioInitializationAntennaLocation UMETA(DisplayName = "Radio Initialization Antenna Location") = 63104U,
	RadioInitializationAntennaPatternType UMETA(DisplayName = "Radio Initialization Antenna Pattern Type") = 63105U,
	RadioInitializationAntennaPatternLength UMETA(DisplayName = "Radio Initialization Antenna Pattern Length") = 63106U,
	RadioInitializationBeamDefinition UMETA(DisplayName = "Radio Initialization Beam Definition") = 63107U,
	RadioInitializationTransmitHeartbeatTime UMETA(DisplayName = "Radio Initialization Transmit Heartbeat Time") = 63108U,
	RadioInitializationTransmitDistanceThresholdVariableRecord UMETA(DisplayName = "Radio Initialization Transmit Distance Threshold Variable Record") = 63109U,
	RadioChannelInitializationLockoutID UMETA(DisplayName = "Radio Channel Initialization Lockout ID") = 63110U,
	RadioChannelInitializationHopsetID UMETA(DisplayName = "Radio Channel Initialization Hopset ID") = 63111U,
	RadioChannelInitializationPresetFrequency UMETA(DisplayName = "Radio Channel Initialization Preset Frequency") = 63112U,
	RadioChannelInitializationFrequencySyncTime UMETA(DisplayName = "Radio Channel Initialization Frequency Sync Time") = 63113U,
	RadioChannelInitializationComsecKey UMETA(DisplayName = "Radio Channel Initialization Comsec Key") = 63114U,
	RadioChannelInitializationAlpha UMETA(DisplayName = "Radio Channel Initialization Alpha") = 63115U,
	AlgorithmParameters UMETA(DisplayName = "Algorithm Parameters") = 70000U,
	DeadReckoningAlgorithmDRA UMETA(DisplayName = "Dead Reckoning Algorithm (DRA)") = 71000U,
	DRALocationThreshold UMETA(DisplayName = "DRA Location Threshold") = 71100U,
	DRAOrientationThreshold UMETA(DisplayName = "DRA Orientation Threshold") = 71200U,
	DRATimeThreshold UMETA(DisplayName = "DRA Time Threshold") = 71300U,
	SimulationManagementParameters UMETA(DisplayName = "Simulation Management Parameters") = 72000U,
	CheckpointInterval UMETA(DisplayName = "Checkpoint Interval") = 72100U,
	TransmitterTimeThreshold UMETA(DisplayName = "Transmitter Time Threshold") = 72600U,
	ReceiverTimeThreshold UMETA(DisplayName = "Receiver Time Threshold") = 72700U,
	InteroperabilityMode UMETA(DisplayName = "Interoperability Mode") = 73000U,
	SIMNETDataCollection UMETA(DisplayName = "SIMNET Data Collection") = 74000U,
	EventID UMETA(DisplayName = "Event ID") = 75000U,
	SourceSiteID UMETA(DisplayName = "Source Site ID") = 75100U,
	SourceHostID UMETA(DisplayName = "Source Host ID") = 75200U,
	ArticulatedParts UMETA(DisplayName = "Articulated Parts") = 90000U,
	PartID UMETA(DisplayName = "Part ID") = 90050U,
	Index UMETA(DisplayName = "Index [UID 55]") = 90070U,
	Position_NewAsWell UMETA(DisplayName = "Position (New As Well)") = 90100U,
	PositionRate UMETA(DisplayName = "Position Rate") = 90200U,
	Extension UMETA(DisplayName = "Extension") = 90300U,
	ExtensionRate UMETA(DisplayName = "Extension Rate") = 90400U,
	X UMETA(DisplayName = "X") = 90500U,
	Xrate UMETA(DisplayName = "X-rate") = 90600U,
	Y UMETA(DisplayName = "Y") = 90700U,
	Yrate UMETA(DisplayName = "Y-rate") = 90800U,
	Z UMETA(DisplayName = "Z") = 90900U,
	Zrate UMETA(DisplayName = "Z-rate") = 91000U,
	Azimuth UMETA(DisplayName = "Azimuth") = 91100U,
	AzimuthRate UMETA(DisplayName = "Azimuth Rate") = 91200U,
	Elevation UMETA(DisplayName = "Elevation") = 91300U,
	ElevationRate UMETA(DisplayName = "Elevation Rate") = 91400U,
	Rotation UMETA(DisplayName = "Rotation") = 91500U,
	RotationRate UMETA(DisplayName = "Rotation Rate") = 91600U,
	DRAAngularXVelocity UMETA(DisplayName = "DRA Angular X-Velocity") = 100001U,
	DRAAngularYVelocity UMETA(DisplayName = "DRA Angular Y-Velocity") = 100002U,
	DRAAngularZVelocity UMETA(DisplayName = "DRA Angular Z-Velocity") = 100003U,
	Appearance_TrailingEffects UMETA(DisplayName = "Appearance, Trailing Effects") = 100004U,
	Appearance_Hatch UMETA(DisplayName = "Appearance, Hatch") = 100005U,
	Appearance_CharacterSet UMETA(DisplayName = "Appearance, Character Set") = 100008U,
	Capability_AmmunitionSupplier UMETA(DisplayName = "Capability, Ammunition Supplier") = 100010U,
	Capability_MiscellaneousSupplier UMETA(DisplayName = "Capability, Miscellaneous Supplier") = 100011U,
	Capability_RepairProvider UMETA(DisplayName = "Capability, Repair Provider") = 100012U,
	ArticulationParameter UMETA(DisplayName = "Articulation Parameter") = 100014U,
	ArticulationParameterType UMETA(DisplayName = "Articulation Parameter Type") = 100047U,
	ArticulationParameterValue UMETA(DisplayName = "Articulation Parameter Value") = 100048U,
	TimeofDayScene UMETA(DisplayName = "Time of Day-Scene") = 100058U,
	LatitudeNorthLocationofweathercell UMETA(DisplayName = "Latitude-North (Location of weather cell)") = 100061U,
	LongitudeEastLocationofweathercell UMETA(DisplayName = "Longitude-East (Location of weather cell)") = 100063U,
	TacticalDriverStatus UMETA(DisplayName = "Tactical Driver Status") = 100068U,
	SonarSystemStatus UMETA(DisplayName = "Sonar System Status") = 100100U,
	Upperlatitude UMETA(DisplayName = "Upper latitude") = 100161U,
	LatitudeSouthLocationofweathercell UMETA(DisplayName = "Latitude-South (Location of weather cell)") = 100162U,
	Westernlongitude UMETA(DisplayName = "Western longitude") = 100163U,
	LongitudeWestlocationofweathercell UMETA(DisplayName = "Longitude-West (location of weather cell)") = 100164U,
	Accomplishedaccept UMETA(DisplayName = "Accomplished accept") = 100160U,
	CDROMNumberDiskIDforterrain UMETA(DisplayName = "CD ROM Number (Disk ID for terrain)") = 100165U,
	DTEDdiskID UMETA(DisplayName = "DTED disk ID") = 100166U,
	Altitude_New UMETA(DisplayName = "Altitude (New)") = 100167U,
	TacticalSystemStatus UMETA(DisplayName = "Tactical System Status") = 100169U,
	JTIDSStatus UMETA(DisplayName = "JTIDS Status") = 100170U,
	TADILJStatus UMETA(DisplayName = "TADIL-J Status") = 100171U,
	DSDDStatus UMETA(DisplayName = "DSDD Status") = 100172U,
	WeaponSystemStatus UMETA(DisplayName = "Weapon System Status") = 100200U,
	Subsystemstatus UMETA(DisplayName = "Subsystem status") = 100205U,
	Numberofinterceptorsfired UMETA(DisplayName = "Number of interceptors fired") = 100206U,
	Numberofinterceptordetonations UMETA(DisplayName = "Number of interceptor detonations") = 100207U,
	Numberofmessagebuffersdropped UMETA(DisplayName = "Number of message buffers dropped") = 100208U,
	Satellitesensorbackgroundyear_day UMETA(DisplayName = "Satellite sensor background (year, day)") = 100213U,
	Satellitesensorbackgroundhour_minute UMETA(DisplayName = "Satellite sensor background (hour, minute)") = 100214U,
	ScriptNumber UMETA(DisplayName = "Script Number") = 100218U,
	Entity_Track_UpdateData UMETA(DisplayName = "Entity/Track/Update Data") = 100300U,
	Local_ForceTraining UMETA(DisplayName = "Local/Force Training") = 100400U,
	Entity_TrackIdentityData UMETA(DisplayName = "Entity/Track Identity Data") = 100500U,
	EntityforTrackEvent UMETA(DisplayName = "Entity for Track Event") = 100510U,
	IFFFriendFoestatus UMETA(DisplayName = "IFF (Friend-Foe) status") = 100520U,
	EngagementData UMETA(DisplayName = "Engagement Data") = 100600U,
	TargetLatitude UMETA(DisplayName = "Target Latitude") = 100610U,
	TargetLongitude UMETA(DisplayName = "Target Longitude") = 100620U,
	AreaofInterestGroundImpactCircleCenterLatitude UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Center Latitude") = 100631U,
	AreaofInterestGroundImpactCircleCenterLongitude UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Center Longitude") = 100632U,
	AreaofInterestGroundImpactCircleRadius UMETA(DisplayName = "Area of Interest (Ground Impact Circle) Radius") = 100633U,
	AreaofInterestType UMETA(DisplayName = "Area of Interest Type") = 100634U,
	TargetAggregateID UMETA(DisplayName = "Target Aggregate ID") = 100640U,
	GICIdentificationNumber UMETA(DisplayName = "GIC Identification Number") = 100650U,
	EstimatedTimeofFlighttoTBMImpact UMETA(DisplayName = "Estimated Time of Flight to TBM Impact") = 100660U,
	EstimatedInterceptTime UMETA(DisplayName = "Estimated Intercept Time") = 100661U,
	EstimatedTimeofFlighttoNextWaypoint UMETA(DisplayName = "Estimated Time of Flight to Next Waypoint") = 100662U,
	Entity_TrackEquipmentData UMETA(DisplayName = "Entity/Track Equipment Data") = 100700U,
	Emission_EWData UMETA(DisplayName = "Emission/EW Data") = 100800U,
	AppearanceData UMETA(DisplayName = "Appearance Data") = 100900U,
	Command_OrderData UMETA(DisplayName = "Command/Order Data") = 101000U,
	EnvironmentalData UMETA(DisplayName = "Environmental Data") = 101100U,
	SignificantEventData UMETA(DisplayName = "Significant Event Data") = 101200U,
	OperatorActionData UMETA(DisplayName = "Operator Action Data") = 101300U,
	ADAEngagementMode UMETA(DisplayName = "ADA Engagement Mode") = 101310U,
	ADAShootingStatus UMETA(DisplayName = "ADA Shooting Status") = 101320U,
	ADAMode UMETA(DisplayName = "ADA Mode") = 101321U,
	ADARadarStatus UMETA(DisplayName = "ADA Radar Status") = 101330U,
	ShootCommand UMETA(DisplayName = "Shoot Command") = 101340U,
	ADAWeaponStatus UMETA(DisplayName = "ADA Weapon Status") = 101350U,
	ADAFiringDisciple UMETA(DisplayName = "ADA Firing Disciple") = 101360U,
	OrderStatus UMETA(DisplayName = "Order Status") = 101370U,
	TimeSynchronization UMETA(DisplayName = "Time Synchronization") = 101400U,
	TomahawkData UMETA(DisplayName = "Tomahawk Data") = 101500U,
	NumberofDetonations UMETA(DisplayName = "Number of Detonations") = 102100U,
	NumberofIntercepts UMETA(DisplayName = "Number of Intercepts") = 102200U,
	OBTControlMT201 UMETA(DisplayName = "OBT Control MT-201") = 200201U,
	SensorDataMT202 UMETA(DisplayName = "Sensor Data MT-202") = 200202U,
	EnvironmentalDataMT203 UMETA(DisplayName = "Environmental Data MT-203") = 200203U,
	OwnshipDataMT204 UMETA(DisplayName = "Ownship Data MT-204") = 200204U,
	AcousticContactDataMT205 UMETA(DisplayName = "Acoustic Contact Data MT-205") = 200205U,
	SonobuoyDataMT207 UMETA(DisplayName = "Sonobuoy Data MT-207") = 200207U,
	SonobuoyContactDataMT210 UMETA(DisplayName = "Sonobuoy Contact Data MT-210") = 200210U,
	HeloControlMT211 UMETA(DisplayName = "Helo Control MT-211") = 200211U,
	ESMControlData UMETA(DisplayName = "ESM Control Data") = 200213U,
	ESMContactDataMT214 UMETA(DisplayName = "ESM Contact Data MT-214") = 200214U,
	ESMEmitterDataMT215 UMETA(DisplayName = "ESM Emitter Data MT-215") = 200215U,
	WeaponDefinitionDataMT217 UMETA(DisplayName = "Weapon Definition Data MT-217") = 200216U,
	WeaponPresetDataMT217 UMETA(DisplayName = "Weapon Preset Data MT-217") = 200217U,
	OBTControlMT301 UMETA(DisplayName = "OBT Control MT-301") = 200301U,
	SensorDataMT302 UMETA(DisplayName = "Sensor Data MT-302") = 200302U,
	EnvironmentalDataMT303m UMETA(DisplayName = "Environmental Data MT-303m") = 200303U,
	OwnshipDataMT304 UMETA(DisplayName = "Ownship Data MT-304") = 200304U,
	AcousticContactDataMT305 UMETA(DisplayName = "Acoustic Contact Data MT-305") = 200305U,
	SonobuoyDataMT307 UMETA(DisplayName = "Sonobuoy Data MT-307") = 200307U,
	SonobuoyContactDataMT310 UMETA(DisplayName = "Sonobuoy Contact Data MT-310") = 200310U,
	HeloScenario_EquipmentStatus UMETA(DisplayName = "Helo Scenario / Equipment Status") = 200311U,
	ESMControlDataMT313 UMETA(DisplayName = "ESM Control Data MT-313") = 200313U,
	ESMContactDataMT314 UMETA(DisplayName = "ESM Contact Data MT-314") = 200314U,
	ESMEmitterDataMT315 UMETA(DisplayName = "ESM Emitter Data MT-315") = 200315U,
	WeaponDefinitionDataMT316 UMETA(DisplayName = "Weapon Definition Data MT-316") = 200316U,
	WeaponPresetDataMT317 UMETA(DisplayName = "Weapon Preset Data MT-317") = 200317U,
	Pairing_AssociationeMT56 UMETA(DisplayName = "Pairing/Association (eMT-56)") = 200400U,
	PointereMT57 UMETA(DisplayName = "Pointer (eMT-57)") = 200401U,
	ReportingResponsibilityeMT58 UMETA(DisplayName = "Reporting Responsibility (eMT-58)") = 200402U,
	TrackNumbereMT59 UMETA(DisplayName = "Track Number (eMT-59)") = 200403U,
	IDforLink11ReportingeMT60 UMETA(DisplayName = "ID for Link-11 Reporting (eMT-60)") = 200404U,
	RemoteTrackeMT62 UMETA(DisplayName = "Remote Track (eMT-62)") = 200405U,
	Link11ErrorRateeMT63 UMETA(DisplayName = "Link-11 Error Rate (eMT-63)") = 200406U,
	TrackQualityeMT64 UMETA(DisplayName = "Track Quality (eMT-64)") = 200407U,
	GridlockeMT65 UMETA(DisplayName = "Gridlock (eMT-65)") = 200408U,
	KilleMT66 UMETA(DisplayName = "Kill (eMT-66)") = 200409U,
	TrackIDChange_ResolutioneMT68 UMETA(DisplayName = "Track ID Change / Resolution (eMT-68)") = 200410U,
	WeaponsStatuseMT69 UMETA(DisplayName = "Weapons Status (eMT-69)") = 200411U,
	Link11OperatoreMT70 UMETA(DisplayName = "Link-11 Operator (eMT-70)") = 200412U,
	ForceTrainingTransmiteMT71 UMETA(DisplayName = "Force Training Transmit (eMT-71)") = 200413U,
	ForceTrainingReceiveeMT72 UMETA(DisplayName = "Force Training Receive (eMT-72)") = 200414U,
	InterceptorAmplificationeMT75 UMETA(DisplayName = "Interceptor Amplification (eMT-75)") = 200415U,
	ConsumableseMT78 UMETA(DisplayName = "Consumables (eMT-78)") = 200416U,
	Link11LocalTrackQualityeMT95 UMETA(DisplayName = "Link-11 Local Track Quality (eMT-95)") = 200417U,
	DLRPeMT19 UMETA(DisplayName = "DLRP (eMT-19)") = 200418U,
	ForceOrdereMT52 UMETA(DisplayName = "Force Order (eMT-52)") = 200419U,
	Wilco_CantcoeMT53 UMETA(DisplayName = "Wilco / Cantco (eMT-53)") = 200420U,
	EMCBearingeMT54 UMETA(DisplayName = "EMC Bearing (eMT-54)") = 200421U,
	ChangeTrackEligibilityeMT55 UMETA(DisplayName = "Change Track Eligibility (eMT-55)") = 200422U,
	LandMassReferencePoint UMETA(DisplayName = "Land Mass Reference Point") = 200423U,
	SystemReferencePoint UMETA(DisplayName = "System Reference Point") = 200424U,
	PUAmplification UMETA(DisplayName = "PU Amplification") = 200425U,
	Set_Drift UMETA(DisplayName = "Set/Drift") = 200426U,
	BeginInitializationMT1 UMETA(DisplayName = "Begin Initialization (MT-1)") = 200427U,
	StatusandControlMT3 UMETA(DisplayName = "Status and Control (MT-3)") = 200428U,
	ScintillationChangeMT39 UMETA(DisplayName = "Scintillation Change (MT-39)") = 200429U,
	Link11IDControlMT61 UMETA(DisplayName = "Link 11 ID Control (MT-61)") = 200430U,
	PUGuardList UMETA(DisplayName = "PU Guard List") = 200431U,
	WindsAloftMT14 UMETA(DisplayName = "Winds Aloft (MT-14)") = 200432U,
	SurfaceWindsMT15 UMETA(DisplayName = "Surface Winds (MT-15)") = 200433U,
	SeaStateMT17 UMETA(DisplayName = "Sea State (MT-17)") = 200434U,
	MagneticVariationMT37 UMETA(DisplayName = "Magnetic Variation (MT-37)") = 200435U,
	TrackEligibilityMT29 UMETA(DisplayName = "Track Eligibility (MT-29)") = 200436U,
	TrainingTrackNotification UMETA(DisplayName = "Training Track Notification") = 200437U,
	TacanDataMT32 UMETA(DisplayName = "Tacan Data (MT-32)") = 200501U,
	InterceptorAmplificationMT75 UMETA(DisplayName = "Interceptor Amplification (MT-75)") = 200502U,
	TacanAssignmentMT76 UMETA(DisplayName = "Tacan Assignment (MT-76)") = 200503U,
	AutopilotStatusMT77 UMETA(DisplayName = "Autopilot Status (MT-77)") = 200504U,
	ConsumablesMT78 UMETA(DisplayName = "Consumables (MT-78)") = 200505U,
	DownlinkMT79 UMETA(DisplayName = "Downlink (MT-79)") = 200506U,
	TINReportMT80 UMETA(DisplayName = "TIN Report (MT-80)") = 200507U,
	SpecialPointControlMT81 UMETA(DisplayName = "Special Point Control (MT-81)") = 200508U,
	ControlDiscretesMT82 UMETA(DisplayName = "Control Discretes (MT-82)") = 200509U,
	RequestTargetDiscretesMT83 UMETA(DisplayName = "Request Target Discretes(MT-83)") = 200510U,
	TargetDiscretesMT84 UMETA(DisplayName = "Target Discretes (MT-84)") = 200511U,
	ReplyDiscretesMT85 UMETA(DisplayName = "Reply Discretes (MT-85)") = 200512U,
	CommandManeuversMT86 UMETA(DisplayName = "Command Maneuvers (MT-86)") = 200513U,
	TargetDataMT87 UMETA(DisplayName = "Target Data (MT-87)") = 200514U,
	TargetPointerMT88 UMETA(DisplayName = "Target Pointer (MT-88)") = 200515U,
	InterceptDataMT89 UMETA(DisplayName = "Intercept Data (MT-89)") = 200516U,
	DecrementMissileInventoryMT90 UMETA(DisplayName = "Decrement Missile Inventory (MT-90)") = 200517U,
	Link4AAlertMT91 UMETA(DisplayName = "Link-4A Alert (MT-91)") = 200518U,
	StrikeControlMT92 UMETA(DisplayName = "Strike Control (MT-92)") = 200519U,
	SpeedChangeMT25 UMETA(DisplayName = "Speed Change (MT-25)") = 200521U,
	CourseChangeMT26 UMETA(DisplayName = "Course Change (MT-26)") = 200522U,
	AltitudeChangeMT27 UMETA(DisplayName = "Altitude Change (MT-27)") = 200523U,
	ACLSAN_SPN46Status UMETA(DisplayName = "ACLS AN/SPN-46 Status") = 200524U,
	ACLSAircraftReport UMETA(DisplayName = "ACLS Aircraft Report") = 200525U,
	SPS67RadarOperatorFunctions UMETA(DisplayName = "SPS-67 Radar Operator Functions") = 200600U,
	SPS55RadarOperatorFunctions UMETA(DisplayName = "SPS-55 Radar Operator Functions") = 200601U,
	SPQ9ARadarOperatorFunctions UMETA(DisplayName = "SPQ-9A Radar Operator Functions") = 200602U,
	SPS49RadarOperatorFunctions UMETA(DisplayName = "SPS-49 Radar Operator Functions") = 200603U,
	MK23RadarOperatorFunctions UMETA(DisplayName = "MK-23 Radar Operator Functions") = 200604U,
	SPS48RadarOperatorFunctions UMETA(DisplayName = "SPS-48 Radar Operator Functions") = 200605U,
	SPS40RadarOperatorFunctions UMETA(DisplayName = "SPS-40 Radar Operator Functions") = 200606U,
	MK95RadarOperatorFunctions UMETA(DisplayName = "MK-95 Radar Operator Functions") = 200607U,
	Kill_NoKill UMETA(DisplayName = "Kill/No Kill") = 200608U,
	CMTpc UMETA(DisplayName = "CMT pc") = 200609U,
	CMC4AirGlobalData UMETA(DisplayName = "CMC4AirGlobalData") = 200610U,
	CMC4GlobalData UMETA(DisplayName = "CMC4GlobalData") = 200611U,
	LINKSIM_COMMENT_PDU UMETA(DisplayName = "LINKSIM_COMMENT_PDU") = 200612U,
	NSSTOwnshipControl UMETA(DisplayName = "NSST Ownship Control") = 200613U,
	Other UMETA(DisplayName = "Other") = 240000U,
	MassOfTheVehicle UMETA(DisplayName = "Mass Of The Vehicle") = 240001U,
	ForceID_New UMETA(DisplayName = "Force ID (New)") = 240002U,
	EntityTypeKind UMETA(DisplayName = "Entity Type Kind") = 240003U,
	EntityTypeDomain UMETA(DisplayName = "Entity Type Domain") = 240004U,
	EntityTypeCountry UMETA(DisplayName = "Entity Type Country") = 240005U,
	EntityTypeCategory UMETA(DisplayName = "Entity Type Category") = 240006U,
	EntityTypeSubCategory UMETA(DisplayName = "Entity Type Sub Category") = 240007U,
	EntityTypeSpecific UMETA(DisplayName = "Entity Type Specific") = 240008U,
	EntityTypeExtra UMETA(DisplayName = "Entity Type Extra") = 240009U,
	AlternativeEntityTypeKind UMETA(DisplayName = "Alternative Entity Type Kind") = 240010U,
	AlternativeEntityTypeDomain UMETA(DisplayName = "Alternative Entity Type Domain") = 240011U,
	AlternativeEntityTypeCountry UMETA(DisplayName = "Alternative Entity Type Country") = 240012U,
	AlternativeEntityTypeCategory UMETA(DisplayName = "Alternative Entity Type Category") = 240013U,
	AlternativeEntityTypeSubCategory UMETA(DisplayName = "Alternative Entity Type Sub Category") = 240014U,
	AlternativeEntityTypeSpecific UMETA(DisplayName = "Alternative Entity Type Specific") = 240015U,
	AlternativeEntityTypeExtra UMETA(DisplayName = "Alternative Entity Type Extra") = 240016U,
	EntityLocationX UMETA(DisplayName = "Entity Location X") = 240017U,
	EntityLocationY UMETA(DisplayName = "Entity Location Y") = 240018U,
	EntityLocationZ UMETA(DisplayName = "Entity Location Z") = 240019U,
	EntityLinearVelocityX UMETA(DisplayName = "Entity Linear Velocity X") = 240020U,
	EntityLinearVelocityY UMETA(DisplayName = "Entity Linear Velocity Y") = 240021U,
	EntityLinearVelocityZ UMETA(DisplayName = "Entity Linear Velocity Z") = 240022U,
	EntityOrientationPsi UMETA(DisplayName = "Entity Orientation Psi") = 240023U,
	EntityOrientationTheta UMETA(DisplayName = "Entity Orientation Theta") = 240024U,
	EntityOrientationPhi UMETA(DisplayName = "Entity Orientation Phi") = 240025U,
	DeadReckoningAlgorithm UMETA(DisplayName = "Dead Reckoning Algorithm") = 240026U,
	DeadReckoningLinearAccelerationX UMETA(DisplayName = "Dead Reckoning Linear Acceleration X") = 240027U,
	DeadReckoningLinearAccelerationY UMETA(DisplayName = "Dead Reckoning Linear Acceleration Y") = 240028U,
	DeadReckoningLinearAccelerationZ UMETA(DisplayName = "Dead Reckoning Linear Acceleration Z") = 240029U,
	DeadReckoningAngularVelocityX UMETA(DisplayName = "Dead Reckoning Angular Velocity X") = 240030U,
	DeadReckoningAngularVelocityY UMETA(DisplayName = "Dead Reckoning Angular Velocity Y") = 240031U,
	DeadReckoningAngularVelocityZ UMETA(DisplayName = "Dead Reckoning Angular Velocity Z") = 240032U,
	EntityAppearance UMETA(DisplayName = "Entity Appearance") = 240033U,
	EntityMarkingCharacterSet UMETA(DisplayName = "Entity Marking Character Set") = 240034U,
	EntityMarking11Bytes UMETA(DisplayName = "Entity Marking 11 Bytes") = 240035U,
	Capability UMETA(DisplayName = "Capability") = 240036U,
	NumberArticulationParameters UMETA(DisplayName = "Number Articulation Parameters") = 240037U,
	ArticulationParameterID UMETA(DisplayName = "Articulation Parameter ID") = 240038U,
	ArticulationParameterType_New UMETA(DisplayName = "Articulation Parameter Type (New)") = 240039U,
	ArticulationParameterValue_New UMETA(DisplayName = "Articulation Parameter Value (New)") = 240040U,
	TypeOfStores UMETA(DisplayName = "Type Of Stores") = 240041U,
	QuantityOfStores UMETA(DisplayName = "Quantity Of Stores") = 240042U,
	FuelQuantity UMETA(DisplayName = "Fuel Quantity") = 240043U,
	RadarSystemStatus UMETA(DisplayName = "Radar System Status") = 240044U,
	RadioCommunicationSystemStatus UMETA(DisplayName = "Radio Communication System Status") = 240045U,
	DefaultTimeForRadioTransmissionForStationaryTransmitters UMETA(DisplayName = "Default Time For Radio Transmission For Stationary Transmitters") = 240046U,
	DefaultTimeForRadioTransmissionForMovingTransmitters UMETA(DisplayName = "Default Time For Radio Transmission For Moving Transmitters") = 240047U,
	BodyPartDamagedRatio UMETA(DisplayName = "Body Part Damaged Ratio") = 240048U,
	NameOfTheTerrainDatabaseFile UMETA(DisplayName = "Name Of The Terrain Database File") = 240049U,
	NameOfLocalFile UMETA(DisplayName = "Name Of Local File") = 240050U,
	AimpointBearing UMETA(DisplayName = "Aimpoint Bearing") = 240051U,
	AimpointElevation UMETA(DisplayName = "Aimpoint Elevation") = 240052U,
	AimpointRange UMETA(DisplayName = "Aimpoint Range") = 240053U,
	AirSpeed UMETA(DisplayName = "Air Speed") = 240054U,
	Altitude_AlsoNew UMETA(DisplayName = "Altitude (Also New)") = 240055U,
	ApplicationStatus UMETA(DisplayName = "Application Status") = 240056U,
	AutoIff UMETA(DisplayName = "Auto Iff") = 240057U,
	BeaconDelay UMETA(DisplayName = "Beacon Delay") = 240058U,
	BingoFuelSetting UMETA(DisplayName = "Bingo Fuel Setting") = 240059U,
	CloudBottom UMETA(DisplayName = "Cloud Bottom") = 240060U,
	CloudTop UMETA(DisplayName = "Cloud Top") = 240061U,
	Direction UMETA(DisplayName = "Direction") = 240062U,
	EndAction UMETA(DisplayName = "End Action") = 240063U,
	Frequency UMETA(DisplayName = "Frequency") = 240064U,
	Freeze UMETA(DisplayName = "Freeze") = 240065U,
	Heading UMETA(DisplayName = "Heading") = 240066U,
	Identification_New UMETA(DisplayName = "Identification (New)") = 240067U,
	InitialPointData UMETA(DisplayName = "Initial Point Data") = 240068U,
	Latitude_New UMETA(DisplayName = "Latitude (New)") = 240069U,
	Lights_New UMETA(DisplayName = "Lights (New)") = 240070U,
	Linear UMETA(DisplayName = "Linear") = 240071U,
	Longitude_New UMETA(DisplayName = "Longitude (New)") = 240072U,
	LowAltitude UMETA(DisplayName = "Low Altitude") = 240073U,
	MfdFormats UMETA(DisplayName = "Mfd Formats") = 240074U,
	Nctr UMETA(DisplayName = "Nctr") = 240075U,
	NumberProjectiles UMETA(DisplayName = "Number Projectiles") = 240076U,
	OperationCode UMETA(DisplayName = "Operation Code") = 240077U,
	Pitch UMETA(DisplayName = "Pitch") = 240078U,
	Profiles UMETA(DisplayName = "Profiles") = 240079U,
	Quantity_AlsoNew UMETA(DisplayName = "Quantity (Also New)") = 240080U,
	RadarModes UMETA(DisplayName = "Radar Modes") = 240081U,
	RadarSearchVolume UMETA(DisplayName = "Radar Search Volume") = 240082U,
	Roll UMETA(DisplayName = "Roll") = 240083U,
	Rotation_New UMETA(DisplayName = "Rotation (New)") = 240084U,
	ScaleFactorX UMETA(DisplayName = "Scale Factor X") = 240085U,
	ScaleFactorY UMETA(DisplayName = "Scale Factor Y") = 240086U,
	Shields UMETA(DisplayName = "Shields") = 240087U,
	Steerpoint UMETA(DisplayName = "Steerpoint") = 240088U,
	Spare1 UMETA(DisplayName = "Spare1") = 240089U,
	Spare2 UMETA(DisplayName = "Spare2") = 240090U,
	Team UMETA(DisplayName = "Team") = 240091U,
	Text UMETA(DisplayName = "Text") = 240092U,
	TimeOfDay UMETA(DisplayName = "Time Of Day") = 240093U,
	TrailFlag UMETA(DisplayName = "Trail Flag") = 240094U,
	TrailSize UMETA(DisplayName = "Trail Size") = 240095U,
	TypeOfProjectile UMETA(DisplayName = "Type Of Projectile") = 240096U,
	TypeOfTarget UMETA(DisplayName = "Type Of Target") = 240097U,
	TypeOfThreat UMETA(DisplayName = "Type Of Threat") = 240098U,
	UhfFrequency UMETA(DisplayName = "Uhf Frequency") = 240099U,
	UtmAltitude UMETA(DisplayName = "Utm Altitude") = 240100U,
	UtmLatitude UMETA(DisplayName = "Utm Latitude") = 240101U,
	UtmLongitude UMETA(DisplayName = "Utm Longitude") = 240102U,
	VhfFrequency UMETA(DisplayName = "Vhf Frequency") = 240103U,
	VisibilityRange UMETA(DisplayName = "Visibility Range") = 240104U,
	VoidAaaHit UMETA(DisplayName = "Void Aaa Hit") = 240105U,
	VoidCollision UMETA(DisplayName = "Void Collision") = 240106U,
	VoidEarthHit UMETA(DisplayName = "Void Earth Hit") = 240107U,
	VoidFriendly UMETA(DisplayName = "Void Friendly") = 240108U,
	VoidGunHit UMETA(DisplayName = "Void Gun Hit") = 240109U,
	VoidRocketHit UMETA(DisplayName = "Void Rocket Hit") = 240110U,
	VoidSamHit UMETA(DisplayName = "Void Sam Hit") = 240111U,
	WeaponData UMETA(DisplayName = "Weapon Data") = 240112U,
	WeaponType UMETA(DisplayName = "Weapon Type") = 240113U,
	Weather_New UMETA(DisplayName = "Weather (New)") = 240114U,
	WindDirection_New UMETA(DisplayName = "Wind Direction (New)") = 240115U,
	WindSpeed UMETA(DisplayName = "Wind Speed") = 240116U,
	WingStation UMETA(DisplayName = "Wing Station") = 240117U,
	Yaw UMETA(DisplayName = "Yaw") = 240118U,
	MemoryOffset UMETA(DisplayName = "Memory Offset") = 240119U,
	MemoryData UMETA(DisplayName = "Memory Data") = 240120U,
	VASI UMETA(DisplayName = "VASI") = 240121U,
	Beacon UMETA(DisplayName = "Beacon") = 240122U,
	Strobe UMETA(DisplayName = "Strobe") = 240123U,
	Culture UMETA(DisplayName = "Culture") = 240124U,
	Approach UMETA(DisplayName = "Approach") = 240125U,
	RunwayEnd UMETA(DisplayName = "Runway End") = 240126U,
	Obstruction UMETA(DisplayName = "Obstruction") = 240127U,
	RunwayEdge UMETA(DisplayName = "Runway Edge") = 240128U,
	RampTaxiway UMETA(DisplayName = "Ramp Taxiway") = 240129U,
	LaserBombCode UMETA(DisplayName = "Laser Bomb Code") = 240130U,
	RackType UMETA(DisplayName = "Rack Type") = 240131U,
	HUD UMETA(DisplayName = "HUD") = 240132U,
	RoleFileName UMETA(DisplayName = "RoleFileName") = 240133U,
	PilotName UMETA(DisplayName = "PilotName") = 240134U,
	PilotDesignation UMETA(DisplayName = "PilotDesignation") = 240135U,
	ModelType UMETA(DisplayName = "Model Type") = 240136U,
	DISType UMETA(DisplayName = "DIS Type") = 240137U,
	Class UMETA(DisplayName = "Class") = 240138U,
	Channel UMETA(DisplayName = "Channel") = 240139U,
	EntityType_New UMETA(DisplayName = "Entity Type (New)") = 240140U,
	AlternativeEntityType_New UMETA(DisplayName = "Alternative Entity Type (New)") = 240141U,
	EntityLocation UMETA(DisplayName = "Entity Location") = 240142U,
	EntityLinearVelocity UMETA(DisplayName = "Entity Linear Velocity") = 240143U,
	EntityOrientation UMETA(DisplayName = "Entity Orientation") = 240144U,
	DeadReckoning UMETA(DisplayName = "Dead Reckoning") = 240145U,
	FailureSymptom UMETA(DisplayName = "Failure Symptom") = 240146U,
	MaxFuel UMETA(DisplayName = "Max Fuel") = 240147U,
	RefuelingBoomConnect UMETA(DisplayName = "Refueling Boom Connect") = 240148U,
	AltitudeAGL UMETA(DisplayName = "Altitude AGL") = 240149U,
	CalibratedAirspeed UMETA(DisplayName = "Calibrated Airspeed") = 240150U,
	TACANChannel UMETA(DisplayName = "TACAN Channel") = 240151U,
	TACANBand UMETA(DisplayName = "TACAN Band") = 240152U,
	TACANMode UMETA(DisplayName = "TACAN Mode") = 240153U,
	Munition UMETA(DisplayName = "Munition") = 500001U,
	EngineFuel UMETA(DisplayName = "Engine Fuel") = 500002U,
	StorageFuel UMETA(DisplayName = "Storage Fuel") = 500003U,
	NotUsed UMETA(DisplayName = "Not Used") = 500004U,
	Expendable UMETA(DisplayName = "Expendable") = 500005U,
	TotalRecordSets UMETA(DisplayName = "Total Record Sets") = 500006U,
	LaunchedMunition UMETA(DisplayName = "Launched Munition") = 500007U,
	Association UMETA(DisplayName = "Association") = 500008U,
	Sensor UMETA(DisplayName = "Sensor") = 500009U,
	MunitionReload UMETA(DisplayName = "Munition Reload") = 500010U,
	EngineFuelReload UMETA(DisplayName = "Engine Fuel Reload") = 500011U,
	StorageFuelReload UMETA(DisplayName = "Storage Fuel Reload") = 500012U,
	ExpendableReload UMETA(DisplayName = "Expendable Reload") = 500013U,
};