// Copyright 2022 Gaming Research Integration for Learning Lab. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"

//Blueprints don't currently support non-uint8 enums.
enum class EWarheadType : uint16
{
	Other,
	CargoVariableSubmunitions UMETA(DisplayName = "Cargo (Variable Submunitions)") = 10U,
	Fuel_AirExplosive UMETA(DisplayName = "Fuel/Air Explosive") = 20U,
	GlassBeads UMETA(DisplayName = "Glass Beads") = 30U,
	OneUm UMETA(DisplayName = "1 um") = 31U,
	FiveUm UMETA(DisplayName = "5 um") = 32U,
	TenUm UMETA(DisplayName = "10 um") = 33U,
	HighExplosiveHE UMETA(DisplayName = "High Explosive (HE)") = 1000U,
	HE_Plastic UMETA(DisplayName = "HE, Plastic") = 1100U,
	HE_Incendiary UMETA(DisplayName = "HE, Incendiary") = 1200U,
	HE_Fragmentation UMETA(DisplayName = "HE, Fragmentation") = 1300U,
	HE_Antitank UMETA(DisplayName = "HE, Antitank") = 1400U,
	HE_Bomblets UMETA(DisplayName = "HE, Bomblets") = 1500U,
	HE_ShapedCharge UMETA(DisplayName = "HE, Shaped Charge") = 1600U,
	HE_ContinuousRod UMETA(DisplayName = "HE, Continuous Rod") = 1610U,
	HE_TungstenBall UMETA(DisplayName = "HE, Tungsten Ball") = 1615U,
	HE_BlastFragmentation UMETA(DisplayName = "HE, Blast Fragmentation") = 1620U,
	HE_SteerableDartswithHE UMETA(DisplayName = "HE, Steerable Darts with HE") = 1625U,
	HE_Darts UMETA(DisplayName = "HE, Darts") = 1630U,
	HE_Flechettes UMETA(DisplayName = "HE, Flechettes") = 1635U,
	HE_DirectedFragmentation UMETA(DisplayName = "HE, Directed Fragmentation") = 1640U,
	HE_SemiArmorPiercingSAP UMETA(DisplayName = "HE, Semi-Armor Piercing (SAP)") = 1645U,
	HE_ShapedChargeFragmentation UMETA(DisplayName = "HE, Shaped Charge Fragmentation") = 1650U,
	HE_SemiArmorPiercing_Fragmentation UMETA(DisplayName = "HE, Semi-Armor Piercing, Fragmentation") = 1655U,
	HE_HollowCharge UMETA(DisplayName = "HE, Hollow Charge") = 1660U,
	HE_DoubleHollowCharge UMETA(DisplayName = "HE, Double Hollow Charge") = 1665U,
	HE_GeneralPurpose UMETA(DisplayName = "HE, General Purpose") = 1670U,
	HE_BlastPenetrator UMETA(DisplayName = "HE, Blast Penetrator") = 1675U,
	HE_RodPenetrator UMETA(DisplayName = "HE, Rod Penetrator") = 1680U,
	HE_Antipersonnel UMETA(DisplayName = "HE, Antipersonnel") = 1685U,
	HE_ShapedCharge_Fragmentation_Incendiary UMETA(DisplayName = "HE, Shaped Charge, Fragmentation, Incendiary") = 1690U,
	HE_Penetrator_Blast_Fragmentation UMETA(DisplayName = "HE, Penetrator, Blast, Fragmentation") = 1695U,
	Smoke UMETA(DisplayName = "Smoke") = 2000U,
	Illumination UMETA(DisplayName = "Illumination") = 3000U,
	Practice UMETA(DisplayName = "Practice") = 4000U,
	Kinetic UMETA(DisplayName = "Kinetic") = 5000U,
	Mines UMETA(DisplayName = "Mines") = 6000U,
	Nuclear UMETA(DisplayName = "Nuclear") = 7000U,
	Nuclear_IMT UMETA(DisplayName = "Nuclear, IMT") = 7010U,
	Chemical_General UMETA(DisplayName = "Chemical, General") = 8000U,
	Chemical_BlisterAgent UMETA(DisplayName = "Chemical, Blister Agent") = 8100U,
	HDMustard UMETA(DisplayName = "HD (Mustard)") = 8110U,
	ThickenedHDMustard UMETA(DisplayName = "Thickened HD (Mustard)") = 8115U,
	DustyHDMustard UMETA(DisplayName = "Dusty HD (Mustard)") = 8120U,
	Chemical_BloodAgent UMETA(DisplayName = "Chemical, Blood Agent") = 8200U,
	ACHCN UMETA(DisplayName = "AC (HCN)") = 8210U,
	CKCNCI UMETA(DisplayName = "CK (CNCI)") = 8215U,
	CGPhosgene UMETA(DisplayName = "CG (Phosgene)") = 8220U,
	Chemical_NerveAgent UMETA(DisplayName = "Chemical, Nerve Agent") = 8300U,
	VX UMETA(DisplayName = "VX") = 8310U,
	ThickenedVX UMETA(DisplayName = "Thickened VX") = 8315U,
	DustyVX UMETA(DisplayName = "Dusty VX") = 8320U,
	GATabun UMETA(DisplayName = "GA (Tabun)") = 8325U,
	ThickenedGATabun UMETA(DisplayName = "Thickened GA (Tabun)") = 8330U,
	DustyGATabun UMETA(DisplayName = "Dusty GA (Tabun)") = 8335U,
	GBSarin UMETA(DisplayName = "GB (Sarin)") = 8340U,
	ThickenedGBSarin UMETA(DisplayName = "Thickened GB (Sarin)") = 8345U,
	DustyGBSarin UMETA(DisplayName = "Dusty GB (Sarin)") = 8350U,
	GDSoman UMETA(DisplayName = "GD (Soman)") = 8355U,
	ThickenedGDSoman UMETA(DisplayName = "Thickened GD (Soman)") = 8360U,
	DustyGDSoman UMETA(DisplayName = "Dusty GD (Soman)") = 8365U,
	GF UMETA(DisplayName = "GF") = 8370U,
	ThickenedGF UMETA(DisplayName = "Thickened GF") = 8375U,
	DustyGF UMETA(DisplayName = "Dusty GF") = 8380U,
	Biological UMETA(DisplayName = "Biological") = 9000U,
	Biological_Virus UMETA(DisplayName = "Biological, Virus") = 9100U,
	Biological_Bacteria UMETA(DisplayName = "Biological, Bacteria") = 9200U,
	Biological_Rickettsia UMETA(DisplayName = "Biological, Rickettsia") = 9300U,
	Biological_GeneticallyModifiedMicroorganisms UMETA(DisplayName = "Biological, Genetically Modified Micro-organisms") = 9400U,
	Biological_Toxin UMETA(DisplayName = "Biological, Toxin") = 9500U,
};