// Copyright 2022 Gaming Research Integration for Learning Lab. All Rights Reserved.

#pragma once
#include "CoreMinimal.h"
#include "WarheadType.generated.h"

//Blueprints don't currently support non-uint8 enums.
UENUM()
enum class EWarheadType : uint16
{
	Other,
	CargoVariableSubmunitions = 10U UMETA(DisplayName = "Cargo (Variable Submunitions)"),
	Fuel_AirExplosive = 20U UMETA(DisplayName = "Fuel/Air Explosive"),
	GlassBeads = 30U UMETA(DisplayName = "Glass Beads"),
	OneUm = 31U UMETA(DisplayName = "1 um"),
	FiveUm = 32U UMETA(DisplayName = "5 um"),
	TenUm = 33U UMETA(DisplayName = "10 um"),
	HighExplosiveHE = 1000U UMETA(DisplayName = "High Explosive (HE)"),
	HE_Plastic = 1100U UMETA(DisplayName = "HE, Plastic"),
	HE_Incendiary = 1200U UMETA(DisplayName = "HE, Incendiary"),
	HE_Fragmentation = 1300U UMETA(DisplayName = "HE, Fragmentation"),
	HE_Antitank = 1400U UMETA(DisplayName = "HE, Antitank"),
	HE_Bomblets = 1500U UMETA(DisplayName = "HE, Bomblets"),
	HE_ShapedCharge = 1600U UMETA(DisplayName = "HE, Shaped Charge"),
	HE_ContinuousRod = 1610U UMETA(DisplayName = "HE, Continuous Rod"),
	HE_TungstenBall = 1615U UMETA(DisplayName = "HE, Tungsten Ball"),
	HE_BlastFragmentation = 1620U UMETA(DisplayName = "HE, Blast Fragmentation"),
	HE_SteerableDartswithHE = 1625U UMETA(DisplayName = "HE, Steerable Darts with HE"),
	HE_Darts = 1630U UMETA(DisplayName = "HE, Darts"),
	HE_Flechettes = 1635U UMETA(DisplayName = "HE, Flechettes"),
	HE_DirectedFragmentation = 1640U UMETA(DisplayName = "HE, Directed Fragmentation"),
	HE_SemiArmorPiercingSAP = 1645U UMETA(DisplayName = "HE, Semi-Armor Piercing (SAP)"),
	HE_ShapedChargeFragmentation = 1650U UMETA(DisplayName = "HE, Shaped Charge Fragmentation"),
	HE_SemiArmorPiercing_Fragmentation = 1655U UMETA(DisplayName = "HE, Semi-Armor Piercing, Fragmentation"),
	HE_HollowCharge = 1660U UMETA(DisplayName = "HE, Hollow Charge"),
	HE_DoubleHollowCharge = 1665U UMETA(DisplayName = "HE, Double Hollow Charge"),
	HE_GeneralPurpose = 1670U UMETA(DisplayName = "HE, General Purpose"),
	HE_BlastPenetrator = 1675U UMETA(DisplayName = "HE, Blast Penetrator"),
	HE_RodPenetrator = 1680U UMETA(DisplayName = "HE, Rod Penetrator"),
	HE_Antipersonnel = 1685U UMETA(DisplayName = "HE, Antipersonnel"),
	HE_ShapedCharge_Fragmentation_Incendiary = 1690U UMETA(DisplayName = "HE, Shaped Charge, Fragmentation, Incendiary"),
	HE_Penetrator_Blast_Fragmentation = 1695U UMETA(DisplayName = "HE, Penetrator, Blast, Fragmentation"),
	Smoke = 2000U UMETA(DisplayName = "Smoke"),
	Illumination = 3000U UMETA(DisplayName = "Illumination"),
	Practice = 4000U UMETA(DisplayName = "Practice"),
	Kinetic = 5000U UMETA(DisplayName = "Kinetic"),
	Mines = 6000U UMETA(DisplayName = "Mines"),
	Nuclear = 7000U UMETA(DisplayName = "Nuclear"),
	Nuclear_IMT = 7010U UMETA(DisplayName = "Nuclear, IMT"),
	Chemical_General = 8000U UMETA(DisplayName = "Chemical, General"),
	Chemical_BlisterAgent = 8100U UMETA(DisplayName = "Chemical, Blister Agent"),
	HDMustard = 8110U UMETA(DisplayName = "HD (Mustard)"),
	ThickenedHDMustard = 8115U UMETA(DisplayName = "Thickened HD (Mustard)"),
	DustyHDMustard = 8120U UMETA(DisplayName = "Dusty HD (Mustard)"),
	Chemical_BloodAgent = 8200U UMETA(DisplayName = "Chemical, Blood Agent"),
	ACHCN = 8210U UMETA(DisplayName = "AC (HCN)"),
	CKCNCI = 8215U UMETA(DisplayName = "CK (CNCI)"),
	CGPhosgene = 8220U UMETA(DisplayName = "CG (Phosgene)"),
	Chemical_NerveAgent = 8300U UMETA(DisplayName = "Chemical, Nerve Agent"),
	VX = 8310U UMETA(DisplayName = "VX"),
	ThickenedVX = 8315U UMETA(DisplayName = "Thickened VX"),
	DustyVX = 8320U UMETA(DisplayName = "Dusty VX"),
	GATabun = 8325U UMETA(DisplayName = "GA (Tabun)"),
	ThickenedGATabun = 8330U UMETA(DisplayName = "Thickened GA (Tabun)"),
	DustyGATabun = 8335U UMETA(DisplayName = "Dusty GA (Tabun)"),
	GBSarin = 8340U UMETA(DisplayName = "GB (Sarin)"),
	ThickenedGBSarin = 8345U UMETA(DisplayName = "Thickened GB (Sarin)"),
	DustyGBSarin = 8350U UMETA(DisplayName = "Dusty GB (Sarin)"),
	GDSoman = 8355U UMETA(DisplayName = "GD (Soman)"),
	ThickenedGDSoman = 8360U UMETA(DisplayName = "Thickened GD (Soman)"),
	DustyGDSoman = 8365U UMETA(DisplayName = "Dusty GD (Soman)"),
	GF = 8370U UMETA(DisplayName = "GF"),
	ThickenedGF = 8375U UMETA(DisplayName = "Thickened GF"),
	DustyGF = 8380U UMETA(DisplayName = "Dusty GF"),
	Biological = 9000U UMETA(DisplayName = "Biological"),
	Biological_Virus = 9100U UMETA(DisplayName = "Biological, Virus"),
	Biological_Bacteria = 9200U UMETA(DisplayName = "Biological, Bacteria"),
	Biological_Rickettsia = 9300U UMETA(DisplayName = "Biological, Rickettsia"),
	Biological_GeneticallyModifiedMicroorganisms = 9400U UMETA(DisplayName = "Biological, Genetically Modified Micro-organisms"),
	Biological_Toxin = 9500U UMETA(DisplayName = "Biological, Toxin")
};